import {GAME_SOURCE_PATHS} from './build-sources.mjs';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
const read=p=>readFile(new URL(p,import.meta.url),'utf8');
const [template,css,...sources]=await Promise.all(['src/template.html','src/styles.css',...GAME_SOURCE_PATHS].map(read));
const js=sources.join('\n').replace(/^export /gm,'').replace(/^import .*;\s*$/gm,'');
if(/<\/script/i.test(js))throw new Error('Unsafe inline script terminator');
const html=template.replace('/* STYLES */',css).replace('/* SCRIPT */',`(()=>{'use strict';\n${js}\n})();`);
await mkdir(new URL('dist/',import.meta.url),{recursive:true});await writeFile(new URL('dist/index.html',import.meta.url),html);
await writeFile(new URL('dist/关掉广告.html',import.meta.url),html);
console.log(`Built dist/index.html (${Buffer.byteLength(html)} bytes), all assets inline.`);
