import test from 'node:test';
import assert from 'node:assert/strict';
import {initialState,reduce,STAGE_COUNT,stageAdIds} from '../src/engine.mjs';
const act=(s,type,value)=>reduce(s,{type,value});
const select=stage=>act(initialState(),'stage.select',stage);
const sequence=(s,actions)=>actions.reduce((state,[type,value])=>act(state,type,value),s);
export const advancedSolutions={
 6:[['service.official'],['service.slot','sat-am'],['service.speed'],['service.review'],['service.submit'],['service.verify']],
 7:[['job.open','qinghe'],['job.contact'],['job.referral'],['job.review'],['job.submit'],['job.verify']],
 8:[['travel.open','river'],['travel.extra','insurance'],['travel.extra','shuttle'],['travel.extra','club'],['travel.review'],['travel.submit'],['travel.verify']]
};
test('nine stages are unlocked with six initial ad units and bounded follow-up for each advanced stage',()=>{assert.equal(STAGE_COUNT,9);for(const stage of [6,7,8]){const s=select(stage);assert.equal(s.stage,stage);assert.equal(s.screen,'play');assert.equal(stageAdIds(stage).length,7);assert.equal(s.adOverlays.length,1);}});
test('each advanced task requires verified receipt and can finish independently',()=>{for(const stage of [6,7,8]){let s=select(stage);const actions=advancedSolutions[stage];s=sequence(s,actions.slice(0,-1));assert.equal(s.screen,'play');const key={6:'service',7:'job',8:'travel'}[stage];assert.equal(s[key].step,'receipt');assert.ok(s[key].receipt);s=sequence(s,actions.slice(-1));assert.equal(s.screen,'debrief');assert.deepEqual(s.completed,[stage]);}});
test('service rejects wrong slot and paid speed package, then recovers without starting over',()=>{let s=select(6);s=act(s,'service.submit');assert.equal(s.screen,'play');s=sequence(s,[['service.official'],['service.slot','sun-am'],['service.review'],['service.submit']]);assert.notEqual(s.service.step,'receipt');s=sequence(s,[['service.slot','sat-am'],['service.review'],['service.submit']]);assert.notEqual(s.service.step,'receipt');assert.ok(s.mistakes>=2);s=sequence(s,[['service.speed'],['service.review'],['service.submit'],['service.verify']]);assert.equal(s.screen,'debrief');});
test('job exposes accurate details and rejects non-matching jobs, contacts and paid referrals',()=>{for(const job of ['training','agency']){let s=sequence(select(7),[['job.open',job],['job.contact'],['job.referral'],['job.review'],['job.submit']]);assert.notEqual(s.job.step,'receipt');s=sequence(s,[['job.search'],['job.open','qinghe'],['job.review'],['job.submit'],['job.verify']]);assert.equal(s.screen,'debrief');}let s=sequence(select(7),[['job.open','qinghe'],['job.review'],['job.submit']]);assert.notEqual(s.job.step,'receipt');s=sequence(s,[['job.contact'],['job.referral'],['job.review'],['job.submit'],['job.verify']]);assert.equal(s.screen,'debrief');});
test('travel checks date, departure time, direct route, refunds, total and every optional add-on',()=>{for(const id of ['cheap','late','connection','wrong-day']){let s=sequence(select(8),[['travel.open',id],['travel.extra','insurance'],['travel.extra','shuttle'],['travel.extra','club'],['travel.review'],['travel.submit']]);assert.notEqual(s.travel.step,'receipt',id);s=sequence(s,[['travel.search'],['travel.open','river'],['travel.review'],['travel.submit'],['travel.verify']]);assert.equal(s.screen,'debrief',id);}let s=sequence(select(8),[['travel.open','river'],['travel.review'],['travel.submit']]);assert.notEqual(s.travel.step,'receipt');s=sequence(s,advancedSolutions[8].slice(1));assert.equal(s.screen,'debrief');});
test('review snapshots are invalidated by later choices and receipt cannot be forged out of order',()=>{for(const stage of [6,7,8]){const key={6:'service',7:'job',8:'travel'}[stage];let s=act(select(stage),`${key}.verify`);assert.equal(s.screen,'play');const actions=advancedSolutions[stage];s=sequence(s,actions.slice(0,-3));s=act(s,`${key}.review`);const mutation={6:['service.speed'],7:['job.contact'],8:['travel.extra','club']}[stage];s=sequence(s,[mutation]);assert.equal(s[key].reviewed,false);s=act(s,`${key}.submit`);assert.notEqual(s[key].step,'receipt');}});
test('invalid values and wrong-stage advanced actions do not mutate choices',()=>{for(const stage of [6,7,8]){let s=select(stage);for(const [type,value] of [['service.slot','unknown'],['job.open','unknown'],['travel.open','unknown'],['travel.extra','unknown']])assert.deepEqual(act(s,type,value),s);for(const action of ['service.verify','job.verify','travel.verify'])assert.equal(act(s,action).screen,'play');}});
test('all new detours preserve valid choices and browser escape remains recoverable',()=>{for(const [stage,trap] of [[6,'service.partner'],[6,'service.remote'],[7,'job.vip'],[8,'travel.coupon']]){let s=select(stage);s=act(s,trap);assert.notEqual(s.route,'goal');s=act(s,'browser.return');assert.equal(s.route,'goal');assert.deepEqual(s.adOverlays,[]);s=sequence(s,advancedSolutions[stage]);assert.equal(s.screen,'debrief');}});
test('receipt survives browser navigation while pause, menu and closed tab block advanced actions',()=>{for(const stage of [6,7,8]){let s=sequence(select(stage),advancedSolutions[stage].slice(0,-1));const key={6:'service',7:'job',8:'travel'}[stage];for(const boundary of ['pause','menu.open','browser.close']){const blocked=act(s,boundary);assert.deepEqual(act(blocked,`${key}.verify`),blocked);}s=sequence(s,[['browser.close'],['browser.return'],[`${key}.verify`]]);assert.equal(s.screen,'debrief');}});
test('closing every ad in all possible orders preserves solvability across original and advanced campaigns',()=>{let checked=0;function* perms(xs){if(!xs.length){yield [];return;}for(let i=0;i<xs.length;i++)for(const tail of perms([...xs.slice(0,i),...xs.slice(i+1)]))yield [xs[i],...tail];}for(let stage=2;stage<9;stage++){const ids=stageAdIds(stage);for(const order of perms(ids)){let s=select(stage);s=act(s,'ad.fakeclose',ids.find(id=>id.endsWith('-float')));for(const id of order)s=act(s,'ad.close',id);assert.equal(s.adClosed.length,ids.length);assert.deepEqual(s.adOverlays,[]);if(stage>=6)assert.equal(sequence(s,advancedSolutions[stage]).screen,'debrief');checked++;}}assert.equal(checked,15216);});
test('all service slot and optional-speed combinations have exactly one valid outcome',()=>{for(const slot of ['sat-am','sat-pm','sun-am'])for(const speed of [true,false]){let s=sequence(select(6),[['service.official'],['service.slot',slot]]);if(!speed)s=act(s,'service.speed');s=sequence(s,[['service.review'],['service.submit']]);assert.equal(s.service.step==='receipt',slot==='sat-am'&&!speed,`${slot} speed=${speed}`);}});
test('job acceptance checks every independent permission and fee combination',()=>{for(const selected of ['training','agency','qinghe'])for(const contact of [false,true])for(const referral of [false,true]){let s=act(select(7),'job.open',selected);if(!contact)s=act(s,'job.contact');if(!referral)s=act(s,'job.referral');s=sequence(s,[['job.review'],['job.submit']]);assert.equal(s.job.step==='receipt',selected==='qinghe'&&!contact&&!referral,`${selected} ${contact} ${referral}`);}});
test('travel acceptance checks every independent add-on, renewal and itinerary combination',()=>{for(const selected of ['cheap','late','connection','wrong-day','river'])for(let mask=0;mask<8;mask++){let s=act(select(8),'travel.open',selected);['insurance','shuttle','club'].forEach((key,i)=>{if(!(mask&(1<<i)))s=act(s,'travel.extra',key);});s=sequence(s,[['travel.review'],['travel.submit']]);assert.equal(s.travel.step==='receipt',selected==='river'&&mask===0,`${selected} add-ons=${mask}`);}});
test('only nine distinct verified tasks unlock the complete screen',()=>{let s=initialState();for(const stage of [8,4,1,7,2,0,6,5,3]){s=act(s,'stage.select',stage);const original={0:[['recipe.expand'],['recipe.answer',200]],1:[['pdf.open'],['pdf.save']],2:[['extra','insurance'],['extra','fast'],['extra','trial'],['checkout.review'],['checkout.pay']],3:[['lesson.play'],['lesson.answer','node']],4:[['notifications.settings'],['notifications.block'],['message.open'],['message.ack']],5:[['subscription.manage'],['cancellation.start'],['cancellation.continue'],['cancellation.confirm'],['cancellation.verify']]};s=sequence(s,advancedSolutions[stage]||original[stage]);assert.equal(s.screen,'debrief');if(s.completed.length<9)assert.notEqual(act(s,'next').screen,'complete');}assert.equal(act(s,'next').screen,'complete');assert.equal(new Set(s.completed).size,9);});
