import test from 'node:test';
import assert from 'node:assert/strict';
import {initialState,reduce} from '../src/engine.mjs';
const act=(s,type,value)=>reduce(s,{type,value});
const select=stage=>act(initialState(),'stage.select',stage);
function solve(s){switch(s.stage){case 0:s=act(s,'recipe.expand');return act(s,'recipe.answer',200);case 1:return act(act(s,'pdf.open'),'pdf.save');case 2:for(const value of ['insurance','fast','trial'])s=act(s,'extra',value);return act(act(s,'checkout.review'),'checkout.pay');case 3:return act(act(s,'lesson.play'),'lesson.answer','node');case 4:for(const type of ['notifications.settings','notifications.block','message.open','message.ack'])s=act(s,type);return s;case 5:for(const type of ['subscription.manage','cancellation.start','cancellation.continue','cancellation.confirm','cancellation.verify'])s=act(s,type);return s;}}
test('starts at the selection screen and invalid chapter selections cannot enter play',()=>{const s=initialState();assert.equal(s.screen,'menu');assert.equal(s.hasStarted,false);for(const value of [-1,6,NaN,1.5,'x',null])assert.deepEqual(act(s,'stage.select',value),s);assert.deepEqual(act(s,'menu.resume'),s);});
test('all six chapters can be entered and solved independently from selection',()=>{for(let i=0;i<6;i++){const s=select(i);assert.equal(s.stage,i);assert.equal(s.screen,'play');assert.equal(s.hasStarted,true);const result=solve(s);assert.equal(result.screen,'debrief',String(i));assert.deepEqual(result.completed,[i]);}});
test('return to selection and resume preserves local choices, closed ads and route',()=>{let s=select(2);s=act(s,'extra','insurance');s=act(s,'ad.close','ticket-banner');const before=s;s=act(s,'menu.open');assert.equal(s.screen,'menu');assert.equal(s.extras.insurance,false);s=act(s,'menu.resume');assert.equal(s.screen,'play');assert.deepEqual(s.extras,before.extras);assert.deepEqual(s.adClosed,before.adClosed);});
test('retry resets current chapter without erasing other completions or changing chapter',()=>{let s=solve(select(0));s=act(s,'stage.select',4);s=act(act(s,'notifications.settings'),'notifications.block');s=act(s,'ad.close','inbox-banner');s=act(s,'retry');assert.equal(s.stage,4);assert.equal(s.pushAllowed,true);assert.deepEqual(s.adClosed,[]);assert.deepEqual(s.completed,[0]);assert.equal(s.screen,'play');});
test('finishing only chapter six cannot claim all chapters complete',()=>{let s=act(solve(select(5)),'next');assert.equal(s.screen,'menu');assert.deepEqual(s.completed,[5]);});
test('out-of-order completion reaches the truthful six-task ending',()=>{let s=initialState();for(const stage of [5,1,3,0,4,2])s=solve(act(s,'stage.select',stage));assert.equal(s.completed.length,6);s=act(s,'next');assert.equal(s.screen,'complete');});
test('completed chapters can be retried without duplicating completion records',()=>{let s=solve(select(0));s=solve(act(s,'retry'));assert.deepEqual(s.completed,[0]);});
test('menu blocks game actions and opening it releases pause',()=>{let s=act(select(3),'pause');s=act(s,'menu.open');assert.equal(s.paused,false);assert.equal(s.screen,'menu');assert.deepEqual(act(s,'lesson.play'),s);});
test('advertisement close order is independent and unknown IDs have no effect',()=>{for(const order of [['ticket-banner','ticket-image','ticket-float'],['ticket-float','ticket-banner','ticket-image'],['ticket-image','ticket-float','ticket-banner']]){let s=select(2);for(const id of order)s=act(s,'ad.close',id);assert.deepEqual([...s.adClosed].sort(),[...order].sort());assert.equal(s.screen,'play');assert.deepEqual(act(s,'ad.close','unknown'),s);assert.equal(s.mistakes,0);}});
test('false close opens at most one extra ad and true closes remove specific instances',()=>{let s=select(3);for(let i=0;i<40;i++)s=act(s,'ad.fakeclose','lesson-float');assert.deepEqual(s.adOverlays,['lesson-float','lesson-followup']);assert.ok(s.attention>=15);s=act(s,'ad.close','lesson-float');assert.deepEqual(s.adOverlays,['lesson-followup']);s=act(s,'ad.close','lesson-followup');assert.deepEqual(s.adOverlays,[]);});
test('return to task clears floating ads and ad redirects cannot trap navigation',()=>{let s=select(4);s=act(s,'ad.visit','inbox-banner');assert.equal(s.route,'sponsor');assert.equal(s.sponsorId,'inbox-banner');s=act(s,'browser.return');assert.equal(s.route,'goal');assert.deepEqual(s.adOverlays,[]);assert.equal(s.pushAllowed,true);});
test('inspect, pause and closed tabs prevent advertisement effects',()=>{const s=select(5);const inspected=act(s,'inspect','ad.visit.radio-image');assert.deepEqual(inspected.adClosed,s.adClosed);assert.deepEqual(inspected.adOverlays,s.adOverlays);assert.equal(inspected.route,'goal');for(const boundary of ['pause','browser.close']){const guarded=act(s,boundary);for(const type of ['ad.close','ad.visit','ad.fakeclose'])assert.deepEqual(act(guarded,type,'radio-float'),guarded);}});
