import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const file=p=>readFileSync(new URL('../'+p,import.meta.url),'utf8');
const source=['src/advanced.mjs','src/engine.mjs','src/content.mjs','src/focus.mjs','src/scenes.mjs','src/advanced-scenes.mjs','src/ads.mjs','src/app.js'].map(file).join('\n');
test('game has no active network, permissions, clipboard, real navigation, or storage APIs',()=>{
 for(const pattern of [/\bfetch\s*\(/,/\bXMLHttpRequest\b/,/\bWebSocket\b/,/\bEventSource\b/,/\brequestPermission\s*\(/,/\bgetUserMedia\s*\(/,/\bclipboard\./,/\bwindow\.open\s*\(/,/\blocation\.(?:href|assign|replace)/,/\b(?:localStorage|sessionStorage|indexedDB)\b/,/\bserviceWorker\b/,/\bcreateObjectURL\b/,/\beval\s*\(/,/\bnew Function\b/])assert.doesNotMatch(source,pattern);
});
test('HTML security policy blocks connections, plugins, forms, workers, and frames',()=>{const html=file('src/template.html');for(const directive of ["default-src 'none'","connect-src 'none'","object-src 'none'","form-action 'none'","worker-src 'none'","frame-src 'none'","base-uri 'none'"])assert.ok(html.includes(directive));assert.doesNotMatch(html,/(?:src|href)=["']https?:/);assert.doesNotMatch(source,/<a\b[^>]*(?:download|href=["']https?)/i);});
test('core dialog copy uses a high-contrast final override',()=>{const css=file('src/styles.css');assert.match(css,/\/\* Core copy contrast/);assert.match(css,/\.inspect-facts dt[^}]*color:#4f5c43/);});
test('notification simulation has no timers, observers, background jobs or persistence',()=>{assert.doesNotMatch(source,/\b(?:setTimeout|setInterval|requestAnimationFrame|Worker|Notification|BroadcastChannel)\s*\(/);});
test('specified essential foreground/background pairs meet 4.5:1 by calculation',()=>{
 const luminance=hex=>{const rgb=hex.match(/[a-f\d]{2}/gi).map(x=>parseInt(x,16)/255).map(x=>x<=.04045?x/12.92:((x+.055)/1.055)**2.4);return rgb[0]*.2126+rgb[1]*.7152+rgb[2]*.0722;};
 for(const [fg,bg,label] of [['4f5c43','fffef8','inspector'],['536575','f4f8fb','inbox help'],['5b5468','ffffff','lesson source'],['f0d6d9','733c4f','membership copy'],['fff8f1','733c4f','cancellation button'],['653347','fffaf6','continue cancellation'],['34482b','eaf0d9','mobile goal'],['f1f4e7','242a35','protected feedback'],['6b4454','f0dce1','offer terms'],['366046','ffffff','permission status']]){const l=[luminance(fg),luminance(bg)].sort((a,b)=>b-a),ratio=(l[0]+.05)/(l[1]+.05);assert.ok(ratio>=4.5,`${label}: ${ratio}`);}
});
test('responsive layout includes dedicated narrow-screen goal, stacked scenes and motion opt-out',()=>{const css=file('src/styles.css');assert.match(css,/@media\(max-width:900px\)/);assert.match(css,/\.sidebar\{display:none\}/);assert.match(css,/\.mobile-goalbar\{display:flex/);assert.match(css,/\.retention-options\{grid-template-columns:minmax\(0,1fr\)/);assert.match(css,/button\{min-height:44px;min-width:44px\}/);assert.match(css,/prefers-reduced-motion:reduce/);assert.match(css,/html\[data-reduced=true\]/);});
test('final specific-selector override enforces 44px legacy controls at desktop and tablet widths',()=>{const css=file('src/styles.css');const final=css.slice(css.indexOf('/* Legacy touch target floor'));for(const selector of ['.yellow-small','.game-footer .text-button','.trial-bottom .text-button','.review-button','.help-notice .text-button','.permission-line .text-button','.tab-close','.quiet','.exit-button'])assert.ok(final.includes(selector),selector);assert.match(final,/min-height:44px;min-width:44px/);});
test('campaign motion pauses behind dialogs and respects both reduced-motion controls',()=>{const css=file('src/styles.css');assert.match(css,/html\[data-paused=true\] \.campaign-ad \*\{animation-play-state:paused!important\}/);assert.match(css,/@media\(prefers-reduced-motion:reduce\)\{\.campaign-ad \*/);assert.match(css,/html\[data-reduced=true\] \.campaign-ad \*/);assert.doesNotMatch(file('src/ads.mjs'),/模拟|游戏内|本游戏|虚构|未请求真实/);});
test('narrow campaign layers are bounded by viewport-relative width and protected navigation stacking',()=>{const css=file('src/styles.css');assert.match(css,/\.campaign-overlays\{position:absolute;inset:0;overflow:hidden;pointer-events:none;z-index:5\}/);assert.match(css,/\.campaign-overlays \.campaign-ad\{[^}]*max-width:calc\(100% - 32px\)/);assert.match(css,/\.immersive-browser \.browser-toolbar\{[^}]*z-index:10/);assert.match(css,/\.browser-bookmarks\{[^}]*z-index:10/);});
test('narrow selection retains a reachable global reset after legacy hide rules',()=>{const css=file('src/styles.css');const lastHide=css.lastIndexOf('.selection-controls .menu-quiet:last-child{display:none}');const lastShow=css.lastIndexOf('.selection-controls .menu-quiet:last-child{display:block}');assert.ok(lastShow>lastHide);assert.match(css.slice(lastShow),/\.selection-controls\{flex-wrap:wrap;justify-content:flex-end\}/);});
test('advanced layouts stack at narrow widths and their option controls retain full-size targets',()=>{const css=file('src/styles.css');assert.match(css,/\.advanced-layout\{display:grid;grid-template-columns:minmax\(0,1fr\) 240px/);assert.match(css,/\.advanced-option\{[^}]*min-height:72px/);assert.match(css,/@media\(max-width:760px\)\{\.advanced-layout\{grid-template-columns:minmax\(0,1fr\)/);assert.match(css,/\.advanced-progress\{grid-template-columns:repeat\(2,minmax\(0,1fr\)\)/);});
