import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
const script=['src/advanced.mjs','src/engine.mjs','src/content.mjs','src/focus.mjs','src/scenes.mjs','src/advanced-scenes.mjs','src/ads.mjs','src/app.js'].map(p=>readFileSync(new URL('../'+p,import.meta.url),'utf8')).join('\n').replace(/^export /gm,'').replace(/^import .*;\s*$/gm,'');
function harness(play=true){
 const nodes=new Map(),focus=[],listeners={};
 const el=id=>({id,innerHTML:'',textContent:'',scrollTop:0,dataset:{},open:false,showModal(){this.open=true},close(){this.open=false},addEventListener(){},querySelector(){return null},focus(){focus.push(id)},scrollIntoView(){}});
 for(const id of ['app','dialog','announcer','world'])nodes.set(id,el(id));
 nodes.get('app').querySelector=selector=>({getClientRects(){return [{}]},focus(){focus.push(selector)},scrollIntoView(){}});
 const document={getElementById:id=>nodes.get(id),activeElement:el('active'),addEventListener(type,fn){listeners[type]=fn},querySelector(){return el('query')},documentElement:{dataset:{}}};
 const context=vm.createContext({document,innerWidth:1440,console});
 vm.runInContext(script+'\nglobalThis.api={handleAction,dispatch,closeDialog,checkout,inspect,render,worldContent,getInspections:()=>inspections,getState:()=>state,setState:s=>state=s,setInspect:v=>inspectMode=v};',context);
 if(play)context.api.dispatch('stage.select',0);
 return {api:context.api,document,nodes,focus,listeners};
}
test('canceling restart reached from pause resumes gameplay',()=>{const {api}=harness();api.handleAction('pause');api.handleAction('restart');api.handleAction('dialog.close');assert.equal(api.getState().paused,false);api.dispatch('recipe.expand');assert.equal(api.getState().recipeExpanded,true);});
test('canceling restart reached from exit resumes gameplay',()=>{const {api}=harness();api.handleAction('exit');api.handleAction('restart');api.handleAction('dialog.close');assert.equal(api.getState().paused,false);});
test('rejoining trial is inspectable and inspection does not enable it',()=>{const {api}=harness();const s=api.getState();s.stage=2;s.extras.trial=false;api.setInspect(true);assert.match(api.checkout(),/data-action="trial.add"[^>]*data-inspect="trial.add"/);api.handleAction('trial.add',{dataset:{inspect:'trial.add'}});assert.equal(api.getState().extras.trial,false);assert.equal(api.getState().inspected.includes('trial.add'),true);});
test('return focus to add-on checkbox after inspection',()=>{const {api,document,focus}=harness();document.activeElement={dataset:{extra:'insurance',focus:'extra:insurance'}};api.inspect('extra.insurance');document.activeElement={dataset:{action:'dialog.close'}};api.closeDialog();assert.equal(focus.at(-1),'[data-focus="extra:insurance"]');});
test('chapter has one stable browser inspector and no duplicate external sidebar',()=>{const {nodes}=harness();const html=nodes.get('app').innerHTML;assert.match(html,/data-focus="toolbar:inspect"/);assert.doesNotMatch(html,/class="sidebar"|mobile-goalbar/);});
test('new traps and decisions are intercepted in inspection mode',()=>{for(const [stage,key] of [[3,'trap.play'],[3,'trap.update'],[4,'notifications.block'],[4,'notifications.dismiss.1'],[5,'trap.discount'],[5,'trap.pause'],[5,'cancellation.confirm']]){const {api}=harness();api.getState().stage=stage;api.setInspect(true);const before=JSON.stringify(api.getState());api.handleAction(key,{dataset:{inspect:key}});const after=api.getState();assert.equal(after.inspected.includes(key),true,key);const previous=JSON.parse(before);assert.equal(after.mistakes,previous.mistakes);assert.equal(after.pushAllowed,previous.pushAllowed);assert.deepEqual(JSON.parse(JSON.stringify(after.subscription)),previous.subscription);}});
test('all six scenes and their meaningful subviews have unique focus identities and known inspections',()=>{
 const {api,nodes}=harness();
 const variants=[{stage:0},{stage:0,recipeExpanded:true,layers:['prize','security']},{stage:1},{stage:1,timetableOpen:true},{stage:2},{stage:2,reviewed:true},{stage:3},{stage:3,lessonOpened:true},{stage:4},{stage:4,pushSettings:true,messageOpen:true},{stage:4,pushSettings:true,pushAllowed:false,pushQueue:[],messageOpen:true},...['account','manage','offers','review','receipt'].map(cancelStep=>({stage:5,cancelStep})),{stage:5,screen:'complete'}];
 for(const patch of variants){Object.assign(api.getState(),{screen:'play',layers:[],route:'goal',tabClosed:false},patch);api.render();const html=nodes.get('app').innerHTML;assert.doesNotMatch(html,/undefined|\[object Object\]/);const keys=[...html.matchAll(/data-focus="([^"]+)"/g)].map(m=>m[1]);assert.equal(new Set(keys).size,keys.length,JSON.stringify(patch));for(const [,key] of html.matchAll(/data-inspect="([^"]+)"/g))assert.ok(api.getInspections()[key],key);}
});
test('new scenes complete via actual event routing, including dismiss and quiz suffixes',()=>{
 const {api,nodes}=harness();api.getState().stage=3;
 api.handleAction('trap.play');assert.equal(api.getState().route,'video-ad');api.handleAction('browser.return');api.handleAction('lesson.play');api.handleAction('lesson.answer.node');assert.equal(api.getState().screen,'debrief');
 api.handleAction('next');assert.equal(api.getState().stage,4);api.handleAction('notifications.dismiss.1');assert.deepEqual([...api.getState().pushQueue],[0,2]);api.handleAction('notifications.settings');api.handleAction('notifications.block');api.handleAction('message.open');api.handleAction('message.ack');assert.equal(api.getState().screen,'debrief');
 api.handleAction('next');for(const action of ['subscription.manage','cancellation.start','trap.pause','subscription.manage','cancellation.start','cancellation.continue','cancellation.confirm'])api.handleAction(action);
 assert.match(nodes.get('app').innerHTML,/<dd>已取消<\/dd>/);assert.match(nodes.get('app').innerHTML,/<dt>下次扣费<\/dt><dd>无<\/dd>/);api.handleAction('cancellation.verify');api.handleAction('next');assert.equal(api.getState().stage,6);assert.equal(api.getState().screen,'play');
});
test('mobile inspection toggle preserves its own origin during rerender',()=>{const {api,focus}=harness();api.handleAction('inspect.toggle',{dataset:{action:'inspect.toggle',focus:'toolbar:inspect'}});assert.equal(focus.at(-1),'[data-focus="toolbar:inspect"]');});
test('restart discards an in-progress recipe draft while normal rerenders preserve it',()=>{const {api,nodes}=harness();nodes.set('temperature',{value:'180'});api.handleAction('motion');assert.equal(nodes.get('temperature').value,'180');api.handleAction('pause');api.closeDialog();assert.equal(nodes.get('temperature').value,'180');api.handleAction('restart');api.handleAction('restart.confirm');assert.equal(nodes.get('temperature').value,'');});
test('registered label click in inspect mode returns focus to that checkbox instance',()=>{for(const key of ['insurance','fast']){const {api,document,focus,listeners}=harness();api.getState().stage=2;api.setInspect(true);document.activeElement={dataset:{focus:'toolbar:inspect'}};const input={dataset:{extra:key,focus:`extra:${key}`,inspect:`extra.${key}`}};const label={querySelector:()=>input};let prevented=false;listeners.click({target:{closest:selector=>selector==='.extra-row'?label:null},preventDefault(){prevented=true;}});assert.equal(prevented,true);assert.equal(api.getState().extras[key],true);api.closeDialog();assert.equal(focus.at(-1),`[data-focus="extra:${key}"]`);}});
test('selection renders nine unlocked chapters and entry replaces it with browser-only framing',()=>{const {api,nodes}=harness(false);let html=nodes.get('app').innerHTML;assert.match(html,/class="chapter-menu/);assert.equal((html.match(/data-action="stage.select.\d"/g)||[]).length,9);api.handleAction('stage.select.3');html=nodes.get('app').innerHTML;assert.equal(api.getState().stage,3);assert.doesNotMatch(html,/class="game-header"|class="sidebar"|class="chapter-menu|class="stats"|mobile-goalbar/);assert.match(html,/class="browser immersive-browser"/);assert.match(html,/data-action="menu.open"/);});
test('all simulation disclaimers are below the browser and never inside advertisements',()=>{const {api,nodes}=harness();for(let stage=0;stage<6;stage++){api.handleAction(`stage.select.${stage}`);const html=nodes.get('app').innerHTML;const index=html.indexOf('<footer id="safety-footer"');assert.ok(index>0);assert.doesNotMatch(html.slice(0,index),/模拟|本游戏|游戏内|未请求真实/);assert.match(html.slice(index),/模拟/);}});
test('later chapters render multiple original illustrated and animated ad units',()=>{const {api,nodes}=harness();for(let stage=2;stage<6;stage++){api.handleAction(`stage.select.${stage}`);const html=nodes.get('app').innerHTML;assert.ok((html.match(/data-ad-id=/g)||[]).length>=3,String(stage));assert.match(html,/ad-artwork/);assert.match(html,/ad-animated/);}});
test('browser menu exposes safe controls without leaving the chapter',()=>{const {api,nodes}=harness();api.handleAction('browser.menu');const html=nodes.get('dialog').innerHTML;for(const action of ['pause','retry','motion','help','menu.open'])assert.ok(html.includes(`data-action="${action}"`),action);api.handleAction('menu.open');assert.equal(api.getState().screen,'menu');api.handleAction('menu.resume');assert.equal(api.getState().screen,'play');});
test('new ad controls are inspectable without closing or entering their destination',()=>{const {api}=harness();api.handleAction('stage.select.2');api.setInspect(true);for(const key of ['ad.close.ticket-banner','ad.fakeclose.ticket-float','ad.visit.ticket-image']){api.handleAction(key,{dataset:{inspect:key,focus:key}});assert.equal(api.getState().route,'goal');assert.deepEqual([...api.getState().adClosed],[]);assert.deepEqual([...api.getState().adOverlays],['ticket-float']);api.closeDialog();}});
test('closing both overlaid ads in either order leaves original page and no active overlay',()=>{for(const order of [['lesson-float','lesson-followup'],['lesson-followup','lesson-float']]){const {api,nodes}=harness();api.handleAction('stage.select.3');api.handleAction('ad.fakeclose.lesson-float');assert.deepEqual([...api.getState().adOverlays],['lesson-float','lesson-followup']);for(const id of order)api.handleAction(`ad.close.${id}`);assert.deepEqual([...api.getState().adOverlays],[]);assert.match(nodes.get('app').innerHTML,/data-action="lesson.play"/);assert.doesNotMatch(nodes.get('app').innerHTML,/data-ad-id="lesson-(?:float|followup)"/);}});
test('menu resume preserves a draft and retry clears only the selected chapter',()=>{const {api,nodes}=harness();nodes.set('temperature',{value:'190'});api.handleAction('menu.open');api.handleAction('menu.resume');assert.equal(nodes.get('temperature').value,'190');api.handleAction('stage.select.4');api.handleAction('notifications.settings');api.handleAction('notifications.block');api.handleAction('retry');assert.equal(api.getState().pushAllowed,false);api.handleAction('retry.confirm');assert.equal(api.getState().stage,4);assert.equal(api.getState().pushAllowed,true);assert.equal(api.getState().screen,'play');});
test('ad inspection returns to exact selected close control and never triggers fake close',()=>{const {api,focus}=harness();api.handleAction('stage.select.5');api.setInspect(true);const key='ad.fakeclose.radio-float';api.handleAction(key,{dataset:{focus:key,inspect:key}});assert.deepEqual([...api.getState().adOverlays],['radio-float']);api.closeDialog();assert.equal(focus.at(-1),`[data-focus="${key}"]`);});
test('opening any dialog stops CSS campaigns and closing resumes unless paused',()=>{const {api,document}=harness();api.handleAction('stage.select.2');api.handleAction('browser.menu');assert.equal(document.documentElement.dataset.paused,'true');api.closeDialog();assert.equal(document.documentElement.dataset.paused,'false');api.handleAction('pause');assert.equal(document.documentElement.dataset.paused,'true');api.handleAction('menu.open');assert.equal(api.getState().paused,false);assert.equal(document.documentElement.dataset.paused,'false');});
test('inspection panels describe page effects without repeating simulation disclaimers',()=>{const {api,nodes}=harness();for(const key of Object.keys(api.getInspections())){api.inspect(key);assert.doesNotMatch(nodes.get('dialog').innerHTML,/模拟|虚构|游戏内|本游戏|不会(?:安装或下载|产生付款或更改真实)|真实视频请求/,key);api.closeDialog();}});
test('skip-link control target exists once on selection and inside every chapter',()=>{const {api,nodes}=harness(false);assert.equal((nodes.get('app').innerHTML.match(/id="game-controls"/g)||[]).length,1);api.handleAction('stage.select.3');assert.equal((nodes.get('app').innerHTML.match(/id="game-controls"/g)||[]).length,1);api.handleAction('menu.open');assert.equal((nodes.get('app').innerHTML.match(/id="game-controls"/g)||[]).length,1);});

const advancedActions={6:['service.official','service.slot.sat-am','service.speed','service.review','service.submit','service.verify'],7:['job.open.qinghe','job.contact','job.referral','job.review','job.submit','job.verify'],8:['travel.open.river','travel.extra.insurance','travel.extra.shuttle','travel.extra.club','travel.review','travel.submit','travel.verify']};
test('advanced scenes route every success action and render unique inspected controls at each step',()=>{for(const stage of [6,7,8]){const {api,nodes}=harness();api.handleAction(`stage.select.${stage}`);for(const action of [...advancedActions[stage],'next']){const html=nodes.get('app').innerHTML;assert.doesNotMatch(html,/undefined|\[object Object\]/);const focus=[...html.matchAll(/data-focus="([^"]+)"/g)].map(m=>m[1]);assert.equal(new Set(focus).size,focus.length,`${stage} ${action}`);for(const [,key] of html.matchAll(/data-inspect="([^"]+)"/g))assert.ok(api.getInspections()[key],key);assert.ok(html.includes(`data-action="${action}"`),action);api.handleAction(action);}assert.equal(api.getState().completed.includes(stage),true);}});
test('advanced pages have six independent illustrated campaigns and bottom-only safety copy',()=>{for(const stage of [6,7,8]){const {api,nodes}=harness();api.handleAction(`stage.select.${stage}`);const html=nodes.get('app').innerHTML;assert.equal((html.match(/data-ad-id=/g)||[]).length,6);assert.ok((html.match(/ad-animated/g)||[]).length>=3);assert.match(html,/ad-artwork/);const footer=html.indexOf('<footer id="safety-footer"');assert.doesNotMatch(html.slice(0,footer),/模拟|虚构|游戏内|本游戏/);assert.match(html.slice(footer),/模拟/);}});
test('advanced inspection intercepts every control without editing service, job or trip state',()=>{for(const stage of [6,7,8]){const {api}=harness();api.handleAction(`stage.select.${stage}`);for(const key of advancedActions[stage]){api.setInspect(true);const before=JSON.stringify([api.getState().service,api.getState().job,api.getState().travel]);api.handleAction(key,{dataset:{inspect:key,focus:key}});assert.equal(JSON.stringify([api.getState().service,api.getState().job,api.getState().travel]),before,key);assert.ok(api.getState().inspected.includes(key));api.closeDialog();}}});
test('advanced misleading service and offer pages have bounded lead steps and a working return',()=>{for(const [stage,trap] of [[6,'service.partner'],[6,'service.remote'],[7,'job.vip'],[8,'travel.coupon']]){const {api,nodes}=harness();api.handleAction(`stage.select.${stage}`);api.handleAction(trap);for(let i=0;i<3;i++){assert.match(nodes.get('app').innerHTML,/data-action="advanced.lead"/);api.handleAction('advanced.lead');}assert.equal(api.getState().adLeadStep,2);assert.match(nodes.get('app').innerHTML,/data-action="browser.return"/);api.handleAction('browser.return');assert.equal(api.getState().route,'goal');for(const action of advancedActions[stage])api.handleAction(action);assert.equal(api.getState().screen,'debrief');}});
test('advanced detours show the declared source domain in the browser address',()=>{for(const [stage,action,host] of [[6,'service.partner','songguo-care.example'],[6,'service.remote','fix-now.example'],[7,'job.vip','career-pass.example'],[8,'travel.coupon','go-perks.example']]){const {api,nodes}=harness();api.handleAction(`stage.select.${stage}`);api.handleAction(action);const address=nodes.get('app').innerHTML.match(/<div class="address">(.*?)<\/div>/s)[1];assert.ok(address.includes(host),`${action}: ${address}`);}});
test('advanced subview changes focus the new task content while editing keeps the exact option',()=>{for(const stage of [6,7,8]){const {api,nodes,focus}=harness();api.handleAction(`stage.select.${stage}`);nodes.get('app').querySelector=selector=>{const match=selector.match(/^\[data-focus="([^"]+)"\]$/);return match&&nodes.get('app').innerHTML.includes(`data-focus="${match[1]}"`)?{getClientRects(){return [{}]},focus(){focus.push(selector)},scrollIntoView(){}}:null;};const run=action=>api.handleAction(action,{dataset:{action,focus:action}});for(const action of advancedActions[stage].slice(0,-1)){run(action);if(action===advancedActions[stage][0])assert.equal(focus.at(-1),'[data-focus="advanced:panel"]');if(action.endsWith('.review'))assert.equal(focus.at(-1),'[data-focus="advanced:summary"]');if(action.endsWith('.submit'))assert.equal(focus.at(-1),'[data-focus="advanced:receipt"]');}assert.match(nodes.get('app').innerHTML,/data-focus="advanced:receipt" tabindex="-1"/);}});
test('advanced validation is visible next to the failed action without adding a second live region',()=>{for(const [stage,actions,reason] of [[6,['service.official','service.review'],'先选择检测时段'],[6,['service.official','service.slot.sat-am','service.review','service.submit'],'优先服务会收取'],[7,['job.open.qinghe','job.review','job.submit'],'通讯录授权或付费内推'],[8,['travel.open.river','travel.review','travel.submit'],'合计超过']]){const {api,nodes}=harness();api.handleAction(`stage.select.${stage}`);for(const a of actions)api.handleAction(a);const html=nodes.get('app').innerHTML;const error=html.match(/<p class="advanced-error"[^>]*>(.*?)<\/p>/s);assert.ok(error,`${stage} missing local validation`);assert.ok(error[1].includes(reason));assert.doesNotMatch(error[0],/role="(?:alert|status)"|aria-live=/);assert.ok(html.indexOf(error[0])<html.indexOf('<aside class="advanced-rail"'));const edit={6:'service.speed',7:'job.contact',8:'travel.extra.insurance'}[stage];api.handleAction(edit);assert.doesNotMatch(nodes.get('app').innerHTML,/class="advanced-error"/);}});
test('editing each advanced option after review retains its control focus without scrolling the panel',()=>{for(const [stage,edits] of [[6,['service.slot.sat-pm','service.speed']],[7,['job.contact','job.referral']],[8,['travel.extra.insurance','travel.extra.shuttle','travel.extra.club']]])for(const edit of edits){const {api,nodes,focus}=harness();const scrolls=[];api.handleAction(`stage.select.${stage}`);nodes.get('app').querySelector=selector=>{const match=selector.match(/^\[data-focus="([^"]+)"\]$/);return match&&nodes.get('app').innerHTML.includes(`data-focus="${match[1]}"`)?{getClientRects(){return [{}]},focus(){focus.push(selector)},scrollIntoView(){scrolls.push(selector)}}:null;};for(const action of advancedActions[stage].slice(0,-2))api.handleAction(action,{dataset:{action,focus:action}});const before=scrolls.length;api.handleAction(edit,{dataset:{action:edit,focus:edit}});assert.equal(focus.at(-1),`[data-focus="${edit}"]`,edit);assert.equal(scrolls.length,before,edit);assert.doesNotMatch(nodes.get('app').innerHTML,/data-focus="advanced:summary"/);}});
