import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
const script=['src/engine.mjs','src/content.mjs','src/focus.mjs','src/scenes.mjs','src/ads.mjs','src/app.js'].map(p=>readFileSync(new URL('../'+p,import.meta.url),'utf8')).join('\n').replace(/^export /gm,'').replace(/^import .*;\s*$/gm,'');
function harness(play=true){
 const nodes=new Map(),focus=[],listeners={};
 const el=id=>({id,innerHTML:'',textContent:'',scrollTop:0,dataset:{},open:false,showModal(){this.open=true},close(){this.open=false},addEventListener(){},querySelector(){return null},focus(){focus.push(id)},scrollIntoView(){}});
 for(const id of ['app','dialog','announcer','world'])nodes.set(id,el(id));
 nodes.get('app').querySelector=selector=>({getClientRects(){return [{}]},focus(){focus.push(selector)}});
 const document={getElementById:id=>nodes.get(id),activeElement:el('active'),addEventListener(type,fn){listeners[type]=fn},querySelector(){return el('query')},documentElement:{dataset:{}}};
 const context=vm.createContext({document,innerWidth:1440,console});
 vm.runInContext(script+'\nglobalThis.api={handleAction,dispatch,closeDialog,checkout,inspect,render,worldContent,getInspections:()=>inspections,getState:()=>state,setState:s=>state=s,setInspect:v=>inspectMode=v};',context);
 if(play)context.api.dispatch('stage.select',0);
 return {api:context.api,document,nodes,focus,listeners};
}
test('canceling restart reached from pause resumes gameplay',()=>{const {api}=harness();api.handleAction('pause');api.handleAction('restart');api.handleAction('dialog.close');assert.equal(api.getState().paused,false);api.dispatch('recipe.expand');assert.equal(api.getState().recipeExpanded,true);});
test('canceling restart reached from exit resumes gameplay',()=>{const {api}=harness();api.handleAction('exit');api.handleAction('restart');api.handleAction('dialog.close');assert.equal(api.getState().paused,false);});
test('rejoining trial is inspectable and inspection does not enable it',()=>{const {api}=harness();const s=api.getState();s.stage=2;s.extras.trial=false;api.setInspect(true);assert.match(api.checkout(),/data-action="trial.add"[^>]*data-inspect="trial.add"/);api.handleAction('trial.add',{dataset:{inspect:'trial.add'}});assert.equal(api.getState().extras.trial,false);assert.equal(api.getState().inspected.includes('trial.add'),true);});
test('return focus to add-on checkbox after inspection',()=>{const {api,document,focus}=harness();document.activeElement={dataset:{extra:'insurance',focus:'extra:insurance'}};api.inspect('extra.insurance');document.activeElement={dataset:{action:'dialog.close'}};api.closeDialog();assert.equal(focus.at(-1),'[data-focus="extra:insurance"]');});
test('chapter has one stable browser inspector and no duplicate external sidebar',()=>{const {nodes}=harness();const html=nodes.get('app').innerHTML;assert.match(html,/data-focus="toolbar:inspect"/);assert.doesNotMatch(html,/class="sidebar"|mobile-goalbar/);});
test('new traps and decisions are intercepted in inspection mode',()=>{for(const [stage,key] of [[3,'trap.play'],[3,'trap.update'],[4,'notifications.block'],[4,'notifications.dismiss.1'],[5,'trap.discount'],[5,'trap.pause'],[5,'cancellation.confirm']]){const {api}=harness();api.getState().stage=stage;api.setInspect(true);const before=JSON.stringify(api.getState());api.handleAction(key,{dataset:{inspect:key}});const after=api.getState();assert.equal(after.inspected.includes(key),true,key);const previous=JSON.parse(before);assert.equal(after.mistakes,previous.mistakes);assert.equal(after.pushAllowed,previous.pushAllowed);assert.deepEqual(JSON.parse(JSON.stringify(after.subscription)),previous.subscription);}});
test('all six scenes and their meaningful subviews have unique focus identities and known inspections',()=>{
 const {api,nodes}=harness();
 const variants=[{stage:0},{stage:0,recipeExpanded:true,layers:['prize','security']},{stage:1},{stage:1,timetableOpen:true},{stage:2},{stage:2,reviewed:true},{stage:3},{stage:3,lessonOpened:true},{stage:4},{stage:4,pushSettings:true,messageOpen:true},{stage:4,pushSettings:true,pushAllowed:false,pushQueue:[],messageOpen:true},...['account','manage','offers','review','receipt'].map(cancelStep=>({stage:5,cancelStep})),{stage:5,screen:'complete'}];
 for(const patch of variants){Object.assign(api.getState(),{screen:'play',layers:[],route:'goal',tabClosed:false},patch);api.render();const html=nodes.get('app').innerHTML;assert.doesNotMatch(html,/undefined|\[object Object\]/);const keys=[...html.matchAll(/data-focus="([^"]+)"/g)].map(m=>m[1]);assert.equal(new Set(keys).size,keys.length,JSON.stringify(patch));for(const [,key] of html.matchAll(/data-inspect="([^"]+)"/g))assert.ok(api.getInspections()[key],key);}
});
test('new scenes complete via actual event routing, including dismiss and quiz suffixes',()=>{
 const {api,nodes}=harness();api.getState().stage=3;
 api.handleAction('trap.play');assert.equal(api.getState().route,'video-ad');api.handleAction('browser.return');api.handleAction('lesson.play');api.handleAction('lesson.answer.node');assert.equal(api.getState().screen,'debrief');
 api.handleAction('next');assert.equal(api.getState().stage,4);api.handleAction('notifications.dismiss.1');assert.deepEqual([...api.getState().pushQueue],[0,2]);api.handleAction('notifications.settings');api.handleAction('notifications.block');api.handleAction('message.open');api.handleAction('message.ack');assert.equal(api.getState().screen,'debrief');
 api.handleAction('next');for(const action of ['subscription.manage','cancellation.start','trap.pause','subscription.manage','cancellation.start','cancellation.continue','cancellation.confirm'])api.handleAction(action);
 assert.match(nodes.get('app').innerHTML,/<dd>已取消<\/dd>/);assert.match(nodes.get('app').innerHTML,/<dt>下次扣费<\/dt><dd>无<\/dd>/);api.handleAction('cancellation.verify');api.handleAction('next');assert.equal(api.getState().screen,'menu');
});
test('mobile inspection toggle preserves its own origin during rerender',()=>{const {api,focus}=harness();api.handleAction('inspect.toggle',{dataset:{action:'inspect.toggle',focus:'toolbar:inspect'}});assert.equal(focus.at(-1),'[data-focus="toolbar:inspect"]');});
test('restart discards an in-progress recipe draft while normal rerenders preserve it',()=>{const {api,nodes}=harness();nodes.set('temperature',{value:'180'});api.handleAction('motion');assert.equal(nodes.get('temperature').value,'180');api.handleAction('pause');api.closeDialog();assert.equal(nodes.get('temperature').value,'180');api.handleAction('restart');api.handleAction('restart.confirm');assert.equal(nodes.get('temperature').value,'');});
test('registered label click in inspect mode returns focus to that checkbox instance',()=>{for(const key of ['insurance','fast']){const {api,document,focus,listeners}=harness();api.getState().stage=2;api.setInspect(true);document.activeElement={dataset:{focus:'toolbar:inspect'}};const input={dataset:{extra:key,focus:`extra:${key}`,inspect:`extra.${key}`}};const label={querySelector:()=>input};let prevented=false;listeners.click({target:{closest:selector=>selector==='.extra-row'?label:null},preventDefault(){prevented=true;}});assert.equal(prevented,true);assert.equal(api.getState().extras[key],true);api.closeDialog();assert.equal(focus.at(-1),`[data-focus="extra:${key}"]`);}});
test('selection renders six unlocked chapters and entry replaces it with browser-only framing',()=>{const {api,nodes}=harness(false);let html=nodes.get('app').innerHTML;assert.match(html,/class="chapter-menu/);assert.equal((html.match(/data-action="stage.select.\d"/g)||[]).length,6);api.handleAction('stage.select.3');html=nodes.get('app').innerHTML;assert.equal(api.getState().stage,3);assert.doesNotMatch(html,/class="game-header"|class="sidebar"|class="chapter-menu|class="stats"|mobile-goalbar/);assert.match(html,/class="browser immersive-browser"/);assert.match(html,/data-action="menu.open"/);});
test('all simulation disclaimers are below the browser and never inside advertisements',()=>{const {api,nodes}=harness();for(let stage=0;stage<6;stage++){api.handleAction(`stage.select.${stage}`);const html=nodes.get('app').innerHTML;const index=html.indexOf('<footer id="safety-footer"');assert.ok(index>0);assert.doesNotMatch(html.slice(0,index),/模拟|本游戏|游戏内|未请求真实/);assert.match(html.slice(index),/模拟/);}});
test('later chapters render multiple original illustrated and animated ad units',()=>{const {api,nodes}=harness();for(let stage=2;stage<6;stage++){api.handleAction(`stage.select.${stage}`);const html=nodes.get('app').innerHTML;assert.ok((html.match(/data-ad-id=/g)||[]).length>=3,String(stage));assert.match(html,/ad-artwork/);assert.match(html,/ad-animated/);}});
test('browser menu exposes safe controls without leaving the chapter',()=>{const {api,nodes}=harness();api.handleAction('browser.menu');const html=nodes.get('dialog').innerHTML;for(const action of ['pause','retry','motion','help','menu.open'])assert.ok(html.includes(`data-action="${action}"`),action);api.handleAction('menu.open');assert.equal(api.getState().screen,'menu');api.handleAction('menu.resume');assert.equal(api.getState().screen,'play');});
test('new ad controls are inspectable without closing or entering their destination',()=>{const {api}=harness();api.handleAction('stage.select.2');api.setInspect(true);for(const key of ['ad.close.ticket-banner','ad.fakeclose.ticket-float','ad.visit.ticket-image']){api.handleAction(key,{dataset:{inspect:key,focus:key}});assert.equal(api.getState().route,'goal');assert.deepEqual([...api.getState().adClosed],[]);assert.deepEqual([...api.getState().adOverlays],['ticket-float']);api.closeDialog();}});
test('closing both overlaid ads in either order leaves original page and no active overlay',()=>{for(const order of [['lesson-float','lesson-followup'],['lesson-followup','lesson-float']]){const {api,nodes}=harness();api.handleAction('stage.select.3');api.handleAction('ad.fakeclose.lesson-float');assert.deepEqual([...api.getState().adOverlays],['lesson-float','lesson-followup']);for(const id of order)api.handleAction(`ad.close.${id}`);assert.deepEqual([...api.getState().adOverlays],[]);assert.match(nodes.get('app').innerHTML,/data-action="lesson.play"/);assert.doesNotMatch(nodes.get('app').innerHTML,/data-ad-id="lesson-(?:float|followup)"/);}});
test('menu resume preserves a draft and retry clears only the selected chapter',()=>{const {api,nodes}=harness();nodes.set('temperature',{value:'190'});api.handleAction('menu.open');api.handleAction('menu.resume');assert.equal(nodes.get('temperature').value,'190');api.handleAction('stage.select.4');api.handleAction('notifications.settings');api.handleAction('notifications.block');api.handleAction('retry');assert.equal(api.getState().pushAllowed,false);api.handleAction('retry.confirm');assert.equal(api.getState().stage,4);assert.equal(api.getState().pushAllowed,true);assert.equal(api.getState().screen,'play');});
test('ad inspection returns to exact selected close control and never triggers fake close',()=>{const {api,focus}=harness();api.handleAction('stage.select.5');api.setInspect(true);const key='ad.fakeclose.radio-float';api.handleAction(key,{dataset:{focus:key,inspect:key}});assert.deepEqual([...api.getState().adOverlays],['radio-float']);api.closeDialog();assert.equal(focus.at(-1),`[data-focus="${key}"]`);});
test('opening any dialog stops CSS campaigns and closing resumes unless paused',()=>{const {api,document}=harness();api.handleAction('stage.select.2');api.handleAction('browser.menu');assert.equal(document.documentElement.dataset.paused,'true');api.closeDialog();assert.equal(document.documentElement.dataset.paused,'false');api.handleAction('pause');assert.equal(document.documentElement.dataset.paused,'true');api.handleAction('menu.open');assert.equal(api.getState().paused,false);assert.equal(document.documentElement.dataset.paused,'false');});
test('inspection panels describe page effects without repeating simulation disclaimers',()=>{const {api,nodes}=harness();for(const key of Object.keys(api.getInspections())){api.inspect(key);assert.doesNotMatch(nodes.get('dialog').innerHTML,/模拟|虚构|游戏内|本游戏|不会(?:安装或下载|产生付款或更改真实)|真实视频请求/,key);api.closeDialog();}});
test('skip-link control target exists once on selection and inside every chapter',()=>{const {api,nodes}=harness(false);assert.equal((nodes.get('app').innerHTML.match(/id="game-controls"/g)||[]).length,1);api.handleAction('stage.select.3');assert.equal((nodes.get('app').innerHTML.match(/id="game-controls"/g)||[]).length,1);api.handleAction('menu.open');assert.equal((nodes.get('app').innerHTML.match(/id="game-controls"/g)||[]).length,1);});
