import {serviceSlots,jobCatalog,tripCatalog,tripTotal} from './advanced.mjs';
export const advancedDetourSources={'service-helper':'songguo-care.example','service-remote':'fix-now.example','job-vip':'career-pass.example','travel-coupon':'go-perks.example'};
const advancedMeta=[
 {label:'一次预约',title:'你只是想，\n约个售后。',goal:'约周六上午的官方免费检测',detail:'为松果洗衣机预约松果家电官方售后，周六 10 月 10 日上午到店检测。只要免费检测，不买优先服务。官方域名是 songguo.example。',host:'songguo.example',tab:'售后预约 · 松果家电',task:'一次预约',tag:'VERIFY THE REAL PROVIDER',lesson:'“官方”两个字，也需要核对出处。',takeaway:'把服务名称、提供方、域名和收费条件一起核对。排在前面的推广、客服头像和加速承诺，都不能替代官方来源与最终预约回执。',facts:['搜索结果的排序不代表官方身份。','免费服务也可能预选付费附加项。','提交后核对时段、费用和服务提供方。'],outcome:['售后，约对了。','预约回执','周六上午 · 官方检测 ¥0','来源、时间与费用都对上了'],icon:'⚒'},
 {label:'一份工作',title:'你只是想，\n投份简历。',goal:'投递直招双休岗，零费用零额外授权',detail:'找企业直招、固定底薪至少 ¥6,000 / 月、周末双休的岗位。只投递已有简历，不交培训或内推费，不开放通讯录。',host:'zhiyu.example',tab:'职位搜索 · 职遇',task:'一份工作',tag:'READ BEYOND THE HEADLINE',lesson:'最高收入，和固定底薪不是一回事。',takeaway:'先读招聘主体和完整条件，再看投递涉及的费用与资料范围。职位标题、醒目的薪资与“提升成功率”承诺，未必符合你的选择。',facts:['固定底薪、综合收入与最高收入要分别看。','核对岗位是否企业直招、是否收费。','与投递无关的额外授权可以单独拒绝。'],outcome:['简历，投对了。','投递回执','青禾文具 · ¥0 · 仅现有简历','双休直招，无收费或通讯录授权'],icon:'▣'},
 {label:'一段出行',title:'你只是想，\n周末出趟门。',goal:'周六上午直达，可退且总价 ≤ ¥120',detail:'预订周六 10 月 10 日上午从青原到白沙的直达车。车票须支持出发前 24 小时免费退，预算 ¥120，只要车票，不要附加服务或自动续费。',host:'wanxing.example',tab:'青原 → 白沙 · 晚行客运',task:'一段出行',tag:'COMPARE THE WHOLE JOURNEY',lesson:'最低价，也可能把条件一起换掉了。',takeaway:'用完整行程与最终价格比较方案。日期、出发时段、换乘、退改和后续扣费，都会改变一张票是否真的适合你。',facts:['同一列表可能混入次日票、联程和不可退特惠票。','本次免费会员也可能带来后续扣费。','完成预订后，再核对最终行程和费用。'],outcome:['这一程，刚刚好。','行程回执','周六 09:20 · 直达 ¥108 · 可退','只有车票，无后续扣费'],icon:'↗'}
];
export function installAdvancedContent(chapters,registry){
 chapters.push(...advancedMeta);
 const info=(title,source,target,effect,clue,kind='正常：页面操作')=>({title,source,target,effect,clue,kind});
 const add=(key,...args)=>registry[key]=info(...args);
 add('service.official','打开品牌官方售后','songguo.example · 松果家电','松果家电到店检测预约','打开预约时段与费用选择。','与目标中给出的官方域名一致。');
 add('service.partner','排名靠前，也要看域名',`${advancedDetourSources['service-helper']} · 安修帮推广`,'第三方预约服务','进入服务推荐页，可能继续引导购买优先受理。','名称接近品牌不等于官方；目标域名为 songguo.example。','留意：仿官方推广');
 add('service.remote','客服头像后面是谁？',`${advancedDetourSources['service-remote']} · 修小帮推广`,'远程诊断服务','打开与官方到店检测无关的服务页。','无需跟随这个客服入口，官方预约仍可继续。','留意：客服包装');
 for(const [id,slot] of Object.entries(serviceSlots))add(`service.slot.${id}`,'选择预约时段','松果家电 · 官方预约',slot.label,'更新时段，之前的预约核对失效。','你的安排是周六上午；可以重新选择。');
 add('service.speed','免费检测之外的 ¥39','松果家电 · 可选优先服务','切换 ¥39 优先服务','添加或移除可选服务，并重新核对。','不买优先服务也能预约相同的时段。','留意：默认附加');
 add('service.review','展开完整预约','松果家电 · 预约核对','来源、时间、本次费用','显示完整预约，尚未提交。','每次修改后重新核对。');
 add('service.submit','提交当前预约','松果家电 · 官方预约','预约回执','核对周六上午与免费条件；符合后生成回执。','提交以后仍需查看最终回执。');
 add('service.verify','核对最终预约结果','松果家电 · 预约回执','官方售后、周六上午、¥0','确认回执后完成任务。','以回执中的服务提供方、时段和费用为准。');
 for(const job of jobCatalog)add(`job.open.${job.id}`,`查看${job.company}完整条件`,'zhiyu.example · 职遇职位列表',job.title,'展开招聘主体、固定底薪、工作日和费用。','不要用最高或综合收入替代固定底薪。');
 add('job.search','回到职位列表','职遇 · 全部职位','重新比较岗位','返回列表，已撤掉的附加项保持原样。','可以自由重选，不必重来整关。');
 add('job.contact','投递为什么要通讯录？','职遇 · 推荐设置','切换通讯录推荐授权','开启或关闭额外资料范围，并清除上次核对。','本次只需要已有简历。','留意：无关授权');
 add('job.referral','所谓的成功率提升','职遇 · 职途内推服务','切换 ¥199 内推服务','添加或移除付费服务，并清除上次核对。','企业直投无需这项服务。','留意：付费包装');
 add('job.vip','另一个内推入口',`${advancedDetourSources['job-vip']} · 职途通推广`,'优先内推权益页','离开职位投递，进入付费服务推荐。','内推承诺不能替代岗位要求。','留意：目标替换');
 add('job.review','核对投递内容','职遇 · 投递核对','岗位条件、费用、资料范围','展开完整条件，尚未投递。','固定底薪、双休、直招与免费需要同时满足。');
 add('job.submit','向企业投递','职遇 · 当前岗位','投递回执','检查岗位和附加项是否符合目标。','没有合规回执时仍可修改。');
 add('job.verify','核对投递回执','职遇 · 已投递','青禾文具、¥0、仅现有简历','确认回执后完成任务。','回执同时记录岗位与资料范围。');
 for(const trip of tripCatalog)add(`travel.open.${trip.id}`,'展开完整行程','wanxing.example · 晚行客运',`${trip.code} · ¥${trip.price}`,'查看日期、出发时段、换乘和退票规则。','票价低并不代表日期、时段或退改都符合。');
 add('travel.search','重新比较班次','晚行客运 · 班次列表','全部青原至白沙班次','返回列表，已移除的服务保持移除。','可以比较所有班次，不会丢失已有选择。');
 for(const [key,title,target] of [['insurance','安心出行保障','本次 + ¥20'],['shuttle','到站接驳服务','本次 + ¥18'],['club','晚行 PLUS 试用','本次 ¥0；7 天后 ¥29 / 月自动续费']])add(`travel.extra.${key}`,title,'晚行客运 · 可选服务',target,'切换可选服务，上次费用核对失效。','本次任务只需要车票。','留意：附加服务');
 add('travel.coupon','低价还附带哪些条件？',`${advancedDetourSources['travel-coupon']} · 旅享会推广`,'会员专享低价页','离开车票列表，继续展示权益领取条件。','看到优惠后，仍要核对行程与后续费用。','留意：多步领取');
 add('travel.review','最后看完整价格','晚行客运 · 订单核对','行程、总价、退票与续费','展开订单详情，尚未预订。','所有影响选择的条件都在这里。');
 add('travel.submit','确认这一程','晚行客运 · 当前订单','预订回执','检查全部行程约束与费用，符合后生成回执。','预订后仍需核对回执。');
 add('travel.verify','看见明确的出行结果','晚行客运 · 预订回执','周六 09:20、直达、¥108、可退','确认最终回执后完成任务。','只看“成功”二字不够，完整条件也应对得上。');
 add('advanced.lead','继续之后还有什么？','当前第三方推广页','下一步权益条件','继续展示付费或额外授权条件，不能完成原任务。','已经点了几步，也随时能返回。','留意：多步诱导');
}
const advancedProgress=(steps,current)=>`<nav class="advanced-progress" aria-label="办理进度">${steps.map((label,i)=>`<span class="${i===current?'current':i<current?'done':''}" ${i===current?'aria-current="step"':''}><b>${i<current?'✓':i+1}</b>${label}</span>`).join('')}</nav>`;
const factRows=rows=>`<dl class="advanced-facts">${rows.map(([label,value])=>`<div><dt>${label}</dt><dd>${value}</dd></div>`).join('')}</dl>`;
const optionButton=(ib,action,title,detail,selected,price)=>ib(action,`<span class="option-check" aria-hidden="true">${selected?'✓':'−'}</span><span><b>${title}</b><small>${detail}</small></span><strong>${price}<small>${selected?'已选择':'未选择'}</small></strong>`,'advanced-option',`role="checkbox" aria-checked="${selected}"`);
const validationMessage=v=>v.validation?`<p class="advanced-error" id="advanced-error"><b>请再核对一下</b>${v.validation}</p>`:'';
function serviceBody(s,ib){
 const v=s.service;
 if(v.step==='receipt')return `<section class="advanced-receipt" data-focus="advanced:receipt" tabindex="-1" aria-label="最终回执"><span class="receipt-seal">✓</span><span class="eyebrow">APPOINTMENT CONFIRMED</span><h2>这次，约好了。</h2>${factRows([['服务提供方',v.receipt.provider],['预约时段',v.receipt.slot],['服务项目','松果洗衣机 · 到店检测'],['本次费用','¥0'],['附加服务','无'],['预约编号',v.receipt.code]])}${ib('service.verify','已核对：官方、周六上午、免费 ✓','solid')}<p>需要变更时可通过官方预约中心办理。</p></section>`;
 if(v.step==='search')return `<section class="advanced-panel" data-focus="advanced:panel" tabindex="-1" aria-label="任务内容"><div class="panel-heading"><span class="eyebrow">SERVICE DIRECTORY</span><h2>找到一个，<br>真正对的入口。</h2><p>产品卡片：松果洗衣机 SG-2 · 保修期内<br>品牌官网：<b>songguo.example</b></p></div><div class="search-query"><span aria-hidden="true">⌕</span> 松果洗衣机　官方售后预约</div><article class="provider-result promoted"><div class="result-label"><span>推广 · 安修帮</span><span>songguo-care.example</span></div><h3>松果售后预约中心 · 优先受理</h3><p>专业对接 · 一站式安排 · 免排队更省心</p>${ib('service.partner','在线预约，快速受理 →','provider-cta')}</article><article class="provider-result"><div class="result-label"><span>松果家电</span><span>songguo.example / support</span></div><h3>松果家电 · 官方售后服务</h3><p>保修期内到店检测 ¥0。无需购买额外服务，可在线选择时段。</p>${ib('service.official','查看官方检测预约 →','provider-cta')}</article><aside class="concierge"><span class="concierge-avatar">修</span><div><b>修小帮在线</b><p>等不及到店？先做远程诊断。</p></div>${ib('service.remote','联系在线客服','text-button')}</aside></section>`;
 return `<section class="advanced-panel" data-focus="advanced:panel" tabindex="-1" aria-label="任务内容"><div class="panel-heading"><span class="source-chip">songguo.example · 官方售后</span><h2>把修理这件事，<br>放进周末的日程。</h2><p>青原中心店 · 保修期内到店检测 ¥0</p></div><h3 class="field-heading">1. 选择到店时段</h3><div class="slot-options" role="group" aria-label="预约时段">${Object.entries(serviceSlots).map(([id,slot])=>ib(`service.slot.${id}`,`<span>${slot.label}</span><small>${v.slot===id?'✓ 已选择':'可预约'}</small>`,'slot-choice',`aria-pressed="${v.slot===id}"`)).join('')}</div><h3 class="field-heading">2. 预约服务</h3>${optionButton(ib,'service.speed','优先受理服务','可选。不购买也能在所选时段免费检测。',v.speed,'¥39')}<p class="quiet-detail">检测费用为 ¥0。若检测后需要另行付费维修，应先确认维修方案；本次不预约收费维修。</p>${!v.reviewed?validationMessage(v):''}${ib('service.review','展开预约核对 ↓','advanced-review')} ${v.reviewed?`<div class="advanced-summary" data-focus="advanced:summary" tabindex="-1" role="region" aria-label="提交前核对"><h3>本次预约核对</h3>${factRows([['提供方','松果家电官方售后'],['时间',serviceSlots[v.slot]?.label||'尚未选择'],['检测费用','¥0'],['优先服务',v.speed?'¥39 · 已选':'未选'],['合计',v.speed?'¥39':'¥0']])}${validationMessage(v)}${ib('service.submit','确认并提交预约 →','solid')}</div>`:''}</section>`;
}
function jobBody(s,ib){
 const v=s.job,job=jobCatalog.find(x=>x.id===v.selected);
 if(v.step==='receipt')return `<section class="advanced-receipt" data-focus="advanced:receipt" tabindex="-1" aria-label="最终回执"><span class="receipt-seal">✓</span><span class="eyebrow">APPLICATION RECEIVED</span><h2>这份简历，<br>去到了该去的地方。</h2>${factRows([['招聘方',v.receipt.company+' · 企业直招'],['职位',v.receipt.title],['固定底薪','¥6,500 / 月'],['休息安排','周末双休'],['本次费用','¥0'],['资料范围',v.receipt.scope],['通讯录','未授权'],['投递编号',v.receipt.code]])}${ib('job.verify','核对无误，完成投递任务 ✓','solid')}<p>投递成功不代表录用，请以企业后续沟通为准。</p></section>`;
 if(v.step==='search')return `<section class="advanced-panel" data-focus="advanced:panel" tabindex="-1" aria-label="任务内容"><div class="panel-heading"><span class="eyebrow">FIND YOUR NEXT CHAPTER</span><h2>合适的工作，<br>藏在完整的条件里。</h2><p>青原 · 办公与客服 · 3 个职位</p></div><div class="search-query"><span>⌕</span> 企业直招　文职　双休</div><div class="job-results">${jobCatalog.map((job,i)=>`<article class="job-result"><div class="result-label"><span>${job.tag}</span><span>${i?'今日更新':'优先展示'}</span></div><h3>${job.title}</h3><strong class="salary">${job.headline}</strong><p>${job.company}</p><span class="job-teaser">${i===0?'带教培养 · 快速成长':i===1?'优质资源 · 双休文职':'企业直招 · 双休 · 无投递费用'}</span>${ib(`job.open.${job.id}`,'查看岗位完整条件 →','provider-cta')}</article>`).join('')}</div><aside class="inline-offer"><div><b>想让简历先被看见？</b><p>职途通，给求职加一点“优先”。</p></div>${ib('job.vip','了解内推特权 →','text-button')}</aside></section>`;
 return `<section class="advanced-panel" data-focus="advanced:panel" tabindex="-1" aria-label="任务内容">${ib('job.search','← 返回全部职位','text-button')}<div class="panel-heading"><span class="source-chip">${job.company} · 职位详情</span><h2>${job.title}</h2><strong class="salary">${job.headline}</strong><p>${job.detail}</p></div>${factRows([['招聘主体',job.direct?'企业直接招聘':'人才中介'],['固定底薪',`¥${job.base.toLocaleString('en-US')} / 月`],['休息安排',job.weekends?'周末双休':'每周单休'],['必要费用',job.fee?`¥${job.fee.toLocaleString('en-US')} · 详见岗位条件`:'¥0']])}<h3 class="field-heading">选择投递方式</h3><div class="resume-card"><span>▤</span><div><b>已有简历 · 求职者 042</b><small>将简历投递给所选招聘方，无需填写新信息</small></div></div>${optionButton(ib,'job.contact','发现认识的人','授权通讯录用于关系推荐，与岗位投递无关。',v.contact,'授权')}${optionButton(ib,'job.referral','职途优先内推','可选服务 ¥199；不购买仍可投递。',v.referral,'¥199')}${!v.reviewed?validationMessage(v):''}${ib('job.review','展开投递核对 ↓','advanced-review')}${v.reviewed?`<div class="advanced-summary" data-focus="advanced:summary" tabindex="-1" role="region" aria-label="提交前核对"><h3>这次将提交什么</h3>${factRows([['岗位',job.company+' · '+job.title],['岗位费用',`¥${job.fee}`],['内推服务',v.referral?'¥199':'未选'],['资料范围',v.contact?'已有简历 + 通讯录':'仅现有简历'],['本次费用',`¥${job.fee+(v.referral?199:0)}`]])}${validationMessage(v)}${ib('job.submit','确认投递 →','solid')}</div>`:''}</section>`;
}
function travelBody(s,ib){
 const v=s.travel,trip=tripCatalog.find(x=>x.id===v.selected);
 if(v.step==='receipt')return `<section class="advanced-receipt" data-focus="advanced:receipt" tabindex="-1" aria-label="最终回执"><span class="receipt-seal">✓</span><span class="eyebrow">JOURNEY CONFIRMED</span><h2>只带上，<br>你想要的这一程。</h2><div class="trip-time receipt-trip"><b>09:20<small>青原客运站</small></b><span>直达 →</span><b>10:40<small>白沙客运站</small></b></div>${factRows([['日期',v.receipt.date],['班次',v.receipt.code],['本次总价','¥108'],['附加服务','无'],['后续扣费',v.receipt.recurring],['退票规则',v.receipt.refund]])}${ib('travel.verify','已核对行程、费用与退票规则 ✓','solid')}</section>`;
 if(v.step==='search')return `<section class="advanced-panel" data-focus="advanced:panel" tabindex="-1" aria-label="任务内容"><div class="panel-heading"><span class="eyebrow">A LITTLE WAY FROM HOME</span><h2>青原 <span class="route-arrow">→</span> 白沙</h2><p>目标日期：周六 10 月 10 日 · 上午出发</p></div><div class="travel-sort"><b>价格从低到高</b><span>含相邻日期和联程推荐，请核对</span></div><div class="trip-results">${[...tripCatalog].sort((a,b)=>a.price-b.price).map(trip=>`<article class="trip-result"><div class="result-label"><span>${trip.label}</span><span>${trip.day==='sat'?'周六 10 月 10 日':'周日 10 月 11 日'}</span></div><div class="trip-time"><b>${trip.depart}<small>青原</small></b><span>${trip.direct?'直达 →':'换乘 1 次 →'}</span><b>${trip.arrive}<small>白沙</small></b><strong>¥${trip.price}</strong></div><div class="trip-foot"><span>${trip.refundable?'出发前 24 小时可免费退':'特惠 · 不可退'}</span>${ib(`travel.open.${trip.id}`,'详情与预订 →','provider-cta')}</div></article>`).join('')}</div><aside class="inline-offer"><div><b>低至 ¥49 的另一种出发</b><p>旅享会专属价，领取后查看适用班次。</p></div>${ib('travel.coupon','先领优惠 →','text-button')}</aside></section>`;
 return `<section class="advanced-panel" data-focus="advanced:panel" tabindex="-1" aria-label="任务内容">${ib('travel.search','← 返回全部班次','text-button')}<div class="panel-heading"><span class="source-chip">${trip.code} · ${trip.label}</span><h2>青原 → 白沙</h2><p>${trip.day==='sat'?'周六 10 月 10 日':'周日 10 月 11 日'} · ${trip.depart} 出发 · ${trip.direct?'直达':'需要换乘'}</p></div><div class="trip-rule"><b>退改规则</b><p>${trip.terms}</p></div><h3 class="field-heading">为这一程，再加一点</h3>${optionButton(ib,'travel.extra.insurance','安心出行保障','可选服务。车票不依赖这项保障。',v.extras.insurance,'¥20')}${optionButton(ib,'travel.extra.shuttle','到站接驳','白沙站至城区的可选接驳。',v.extras.shuttle,'¥18')}${optionButton(ib,'travel.extra.club','晚行 PLUS · 7 天试用','7 天后 ¥29 / 月自动续费，需在试用结束前取消。',v.extras.club,'今日 ¥0')}<div class="advanced-total"><span>当前合计<small>预算上限 ¥120</small></span><b>¥${tripTotal(v)}</b></div>${!v.reviewed?validationMessage(v):''}${ib('travel.review','展开全部费用与行程 ↓','advanced-review')}${v.reviewed?`<div class="advanced-summary" data-focus="advanced:summary" tabindex="-1" role="region" aria-label="提交前核对"><h3>确认前，再看完整的一程</h3>${factRows([['日期',trip.day==='sat'?'周六 10 月 10 日':'周日 10 月 11 日'],['出发 / 到达',`${trip.depart} / ${trip.arrive}`],['换乘',trip.direct?'无 · 直达':'1 次'],['车票',`¥${trip.price}`],['附加服务',`¥${tripTotal(v)-trip.price}`],['合计',`¥${tripTotal(v)}`],['后续扣费',v.extras.club?'7 天后 ¥29 / 月':'无'],['退票',trip.terms]])}${validationMessage(v)}${ib('travel.submit','确认预订 →','solid')}</div>`:''}</section>`;
}
export function advancedScene(s,ib,adBlock){
 const index=s.stage-6,meta=advancedMeta[index],key=['service','job','travel'][index],v=s[key];
 const mastheads=['⚒ 松果家电','▣ 职遇','↗ 晚行客运'];
 const current={search:0,form:1,detail:1,review:2,receipt:3}[v.step];
 return `<div class="site advanced-site ${key}-site"><div class="site-masthead advanced-masthead"><span class="site-logo"><b>${mastheads[index]}</b></span><span class="site-edition">${['CARE / OFFICIAL SERVICE','WORK / YOUR NEXT STEP','TRAVEL / GO YOUR OWN WAY'][index]}</span></div><div class="advanced-body">${advancedProgress([['核对来源','选择时段','核对预约','确认回执'],['比较岗位','完整条件','核对投递','确认回执'],['比较班次','完整行程','核对订单','确认回执']][index],current)}<div class="advanced-layout"><div>${[serviceBody,jobBody,travelBody][index](s,ib)}</div><aside class="advanced-rail">${adBlock('rail')}<div class="source-note"><b>本页服务</b><span>${meta.host}</span><p>${index===0?'到店检测预约中心':index===1?'职位详情与已有简历投递':'班次、票价和退改规则查询'}</p></div></aside></div><div class="advanced-ad-grid">${adBlock('native')}${adBlock('strip')}</div></div></div>`;
}
export function advancedDetour(s,ib,button){
 const details={
  'service-helper':{brand:'安修帮',title:'你的预约，值得优先。',intro:'松果机型服务对接 · 受理更省心',steps:['先领取专属受理名额','加入优先受理服务 · ¥79','服务由安修帮提供，非松果家电官方预约'],cta:'领取名额，下一步 →'},
  'service-remote':{brand:'修小帮',title:'先听听，在线工程师怎么说。',intro:'专属诊断通道 · 推荐远程服务',steps:['匹配在线服务顾问','开通远程诊断服务 · ¥59','此服务不能代替官方到店检测'],cta:'继续查看诊断方案 →'},
  'job-vip':{brand:'职途通',title:'下一份机会，想快一点？',intro:'优先曝光 · 专属推荐',steps:['查看优先投递权益','选择内推服务 · ¥199','服务不保证录用，具体岗位条件另行核对'],cta:'继续了解优先权益 →'},
  'travel-coupon':{brand:'旅享会',title:'¥49 起，把周末带走。',intro:'会员专享低价 · 精选班次',steps:['领取会员专享价','加入 7 天试用，之后 ¥29 / 月自动续费','特价仅限周日指定不可退班次'],cta:'继续领取专享价 →'}
 };
 const d=details[s.route];if(!d)return '';
 return `<section class="advanced-detour"><div class="sponsor-masthead"><b>${d.brand}</b><span>推广服务</span></div><span class="detour-orbit" aria-hidden="true">✦</span><span class="eyebrow">A LITTLE MORE, ONE MORE STEP</span><h2>${d.title}</h2><p>${d.intro}</p><ol class="lead-steps">${d.steps.slice(0,s.adLeadStep+1).map((text,i)=>`<li><span>0${i+1}</span>${text}</li>`).join('')}</ol>${ib('advanced.lead',d.cta,'lead-cta')}<div class="detour-exit">${button('browser.return','返回原页面，继续原来的事 →','solid','','advanced:return')}</div></section>`;
}
