import {initialState,reduce,total,STAGE_COUNT} from './engine.mjs';
import {chapters,inspections,sources} from './content.mjs';
import {captureFocus,restoreFocus} from './focus.mjs';
import {lessonScene,notificationScene,subscriptionScene} from './scenes.mjs';
import {adCatalog,renderStageAds,installAdInspections,sponsorScene,chapterArtwork} from './ads.mjs';
import {installAdvancedInspections,advancedScene,advancedDetour,advancedDetourSources} from './advanced-scenes.mjs';
installAdInspections(inspections);
installAdvancedInspections(inspections);
let state=initialState(),inspectMode=false,reduceMotion=false,dialogType='',dialogReturn=null,actionFocus=null,temperatureDraft='';
const app=document.getElementById('app'),dialog=document.getElementById('dialog');
const icons={arrow:'↗',back:'←',close:'×',check:'✓',search:'⌕',pause:'Ⅱ'};
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const button=(action,text,cls='',extra='',focus=action)=>`<button type="button" data-action="${action}" data-focus="${focus}" class="${cls}" ${extra}>${text}</button>`;
const ib=(action,text,cls='',extra='',focus=action)=>button(action,text,cls,`data-inspect="${action}" ${extra}`,focus);
const foodArt=`<svg class="food-art" viewBox="0 0 440 300" role="img" aria-label="原创插画：白盘里的番茄焗意面"><ellipse cx="226" cy="264" rx="151" ry="15" fill="#242d23" opacity=".1"/><path d="M41 32l26 8-14 126-23-3z" fill="#b5c594"/><path d="M371 169l39 12-37 102-41-14z" fill="#fff5d9"/><g transform="translate(228 154) rotate(-12)"><ellipse rx="168" ry="111" fill="#fffbef" stroke="#ddd8c6" stroke-width="3"/><ellipse rx="139" ry="85" fill="#e8e0c8"/><ellipse rx="127" ry="76" fill="#df693f"/><g fill="none" stroke="#ffc96e" stroke-width="13" stroke-linecap="round"><path d="M-106-5q30-48 65-19t55 0 60 6 35 8"/><path d="M-89 22q22-40 50-8t50-5 54 8 24 0"/><path d="M-68-45q25 18 61 0t57 11"/><path d="M-70 42q40-23 68 7t73-11"/></g><g fill="#a53627" stroke="#f58257" stroke-width="3"><circle cx="-77" cy="-30" r="16"/><circle cx="65" cy="-9" r="19"/><circle cx="-17" cy="37" r="16"/></g><g fill="#477652"><path d="M-15-13q-34-30-40-12 5 27 40 12"/><path d="M-15-13q-3-40 15-37 19 17-15 37"/><path d="M73 38q-33-12-37 6 15 20 37-6"/></g><g fill="#fff1c5"><circle cx="-51" cy="6" r="4"/><circle cx="30" cy="26" r="4"/><circle cx="15" cy="-30" r="5"/><circle cx="88" cy="-31" r="4"/></g></g></svg>`;
const ticketArt=`<svg viewBox="0 0 280 150" class="ticket-art" role="img" aria-label="原创插画：明日闲逛馆的橙色门票"><g transform="rotate(-8 140 75)"><path d="M25 24h230v35a16 16 0 000 32v35H25V91a16 16 0 000-32z" fill="#ff8255" stroke="#1d2730" stroke-width="2"/><path d="M195 24v102" stroke="#1d2730" stroke-width="2" stroke-dasharray="5 5"/><text x="47" y="64" font-family="sans-serif" font-size="19" font-weight="bold" fill="#17232a">闲逛许可证</text><text x="47" y="92" font-family="monospace" font-size="11" fill="#17232a">ONE DAY / ONE LITTLE JOY</text><g stroke="#17232a" stroke-width="3"><path d="M212 44v61m8-61v61m7-61v61m8-61v61"/></g></g></svg>`;
function selection(){
 const complete=state.completed.length===STAGE_COUNT;
 return `<main class="chapter-menu" data-focus="menu" tabindex="-1"><header class="selection-header"><div class="selection-brand"><span aria-hidden="true">×</span><b>关掉广告</b><small>VOL. 04</small></div><div class="selection-controls" id="game-controls" tabindex="-1" role="navigation" aria-label="选关操作">${button('help','怎么玩','menu-quiet')}${button('motion',reduceMotion?'动态已减少':'减少动态','menu-quiet',`aria-pressed="${reduceMotion}"`)}${button('restart','重置进度','menu-quiet')}</div></header><section class="selection-intro"><div><span class="eyebrow">A PERFECTLY ORDINARY DAY</span><h1>你今天，<br>只是想做点小事。</h1><p>选一件开始。别让不请自来的热情，<br>带走你原本的打算。</p></div><div class="selection-note"><span class="selection-note-mark" aria-hidden="true">↗</span><b>${complete?'九件小事，都完成了。':'不考手速。<br>记得目的地就好。'}</b><p>${state.completed.length} / ${STAGE_COUNT} 已完成</p>${state.hasStarted?button('menu.resume',`继续${['debrief','complete'].includes(state.returnScreen)?'查看结果':'上一件小事'} →`,'menu-resume','','menu:resume'): '<small>全部关卡开放 · 可以任意顺序玩</small>'}</div></section><div class="selection-grid">${chapters.map((c,i)=>`<button type="button" class="chapter-card chapter-card-${i} ${state.completed.includes(i)?'is-complete':''}" data-action="stage.select.${i}" data-focus="chapter:${i}"><div class="chapter-card-art">${chapterArtwork(i)}<span class="chapter-card-number">0${i+1}</span>${state.completed.includes(i)?'<span class="chapter-done">✓ 已完成</span>':''}</div><div class="chapter-card-copy"><span class="chapter-kicker">${c.label} <span aria-hidden="true">↗</span></span><h2>${c.goal}</h2><p>${c.detail}</p><span class="chapter-open">${state.completed.includes(i)?'再玩这关':'进入这一关'} <span>→</span></span></div></button>`).join('')}</div><div class="selection-bottom"><p>走过弯路也没关系。<br>每一关都有回来的路。</p><div class="menu-stats"><span>已完成 <b>${state.completed.length}</b> 件</span><span>检查过 <b>${state.inspected.length}</b> 处</span><span>找回目标 <b>${state.recoveries}</b> 次</span></div></div></main>`;
}
function safetyFooter(){return `<footer id="safety-footer" class="safety-footer"><b>关于这张网页</b><p>这是一个离线网页游戏。所有网站、品牌、广告、通知、账户、下载和付款均为虚构模拟，仅改变本页状态，不会请求真实设备权限、下载软件、导航到外部网站或产生支付。无需个人信息，没有联网、追踪和数据收集。刷新后进度清空。</p><p>网页中的关闭、返回与标签页操作也仅限游戏。浏览器工具栏里的「选关」「返回原页面」和菜单始终可用；动态效果可以关闭。</p>${button('sources','资料依据','footer-link','','footer:sources')}</footer>`;}
function browser(){
 const c=chapters[state.stage],host=state.route==='goal'?c.host:state.route==='sponsor'?(adCatalog.find(ad=>ad.id===state.sponsorId)?.host||'sponsor.example'):(advancedDetourSources[state.route]||`${state.route}.ad.example`);
 return `<section class="browser immersive-browser" aria-label="浏览器窗口"><div class="browser-top"><div class="traffic" aria-hidden="true"><i></i><i></i><i></i></div><div class="browser-tab"><span class="tab-icon">${c.icon}</span><span>${c.tab}</span>${button('browser.close','×','tab-close','aria-label="关闭标签页" title="关闭标签页"')}</div><span class="browser-newtab" aria-hidden="true">＋</span><span class="window-corner" aria-hidden="true">—　□</span></div><nav class="browser-toolbar" id="game-controls" tabindex="-1" aria-label="浏览器导航">${button('menu.open','⌂','browser-home','aria-label="返回选关" title="返回选关"','toolbar:home')}${button('browser.back','←','browser-back','aria-label="返回上一个页面" title="返回"')}${button('browser.return','↻','browser-reload','aria-label="返回原页面" title="返回原页面"','toolbar:return')}<div class="address"><span aria-hidden="true">▧</span><span>${host}</span><span class="address-star" aria-hidden="true">☆</span></div>${button('browser.menu','⋯','browser-more','aria-label="打开浏览器菜单" title="菜单"','toolbar:menu')}</nav><div class="browser-bookmarks">${button('goal.show',`<span aria-hidden="true">★</span><span>${c.goal}</span>`,'browser-goal','title="查看本关目标"','toolbar:goal')}${button('inspect.toggle',inspectMode?'⌕ 检查中':'⌕ 检查','browser-inspector',`aria-pressed="${inspectMode}"`,'toolbar:inspect')}</div><div id="world" class="world ${inspectMode?'inspect-mode':''}" data-focus="world" tabindex="-1">${worldContent()}</div><div id="feedback" class="feedback browser-status" role="status"><span aria-hidden="true">${state.screen==='play'?'↳':'✓'}</span><span>${state.notice}</span></div></section>`;
}
function decoratePage(html){
 if(state.stage<2)return html;
 const banner=renderStageAds(state,'banner',ib),image=renderStageAds(state,'image',ib);
 const head=html.indexOf('</div>');
 html=html.slice(0,head+6)+banner+html.slice(head+6);
 const end=html.lastIndexOf('</div>');
 return html.slice(0,end)+image+html.slice(end);
}
function worldContent(){
 if(state.screen==='debrief')return debrief();
 if(state.screen==='complete')return complete();
 if(state.tabClosed)return `<section class="detour closed"><span class="detour-icon">□</span><div class="eyebrow">ONE TAB LESS</div><h2>标签页已关闭。</h2><p>关掉一个页面，不等于放弃你的任务。</p>${button('browser.return','重新打开原来的页面 ↗','solid','','closed:return')}</section>`;
 if(state.route==='sponsor')return sponsorScene(state,button);
 if(state.route!=='goal')return (state.stage>=6?advancedDetour(state,ib,button):'')||detour();
 const page=state.stage>=6?advancedScene(state,ib,slot=>renderStageAds(state,slot,ib)):[recipe,school,checkout,()=>lessonScene(state,ib),()=>notificationScene(state,ib),()=>subscriptionScene(state,ib)][state.stage]();
 return decoratePage(page)+adLayers()+`<div class="campaign-overlays">${renderStageAds(state,'overlay',ib)}</div>`;
}
function recipe(){return `<div class="site recipe-site"><div class="site-masthead"><span class="site-logo kitchen-logo">✳ <b>慢半拍</b><small>厨房</small></span><span class="site-nav">认真做饭　/　慢慢吃饭</span></div><div class="recipe-ad ad" aria-label="推广广告"><span class="ad-label">广告 / AD</span><span>晚饭不重要，<b>你的好运更重要！</b></span>${ib('trap.prize','看看我的好运 ↗','yellow-small','','recipe:prize')}</div><div class="recipe-layout"><article><div class="breadcrumb">首页 / 日常食谱 / 烤箱料理</div><span class="eyebrow coral">TONIGHT, SOMETHING GOOD.</span><h2 class="recipe-title">番茄焗意面</h2><p class="recipe-intro">把普通的一天，烤得热气腾腾。</p><div class="recipe-meta"><span class="author-avatar">慢</span><span>慢半拍编辑部<small>家常食谱 · 2026.09.18</small></span><span class="rating">★ 4.9<small>126 人做过</small></span></div><div class="food-scene">${foodArt}<span class="food-sticker">认真吃饭<br><b>很重要</b></span></div><div class="recipe-facts"><span>准备<strong>10 分钟</strong></span><span>烘烤<strong>15 分钟</strong></span><span>份量<strong>2 人份</strong></span></div><div class="method"><div class="section-heading"><h3>原始菜谱 · 做法</h3><span>不用先领券</span></div>${state.recipeExpanded?`<ol class="steps"><li><b>01</b><span>番茄切块，与洋葱炒软，加入少许盐。</span></li><li><b>02</b><span>意面煮至八分熟，拌入番茄酱，铺上芝士。</span></li><li class="temperature-step"><b>03</b><span>烤箱上下火预热至 <strong>200°C</strong>，中层烘烤 15 分钟，表面微金黄即可。</span></li></ol>`:ib('recipe.expand','展开做法 · 3 个步骤 <span>↓</span>','method-button')}<form id="temperature-form" class="answer-form"><label for="temperature">记下烤箱温度</label><div class="answer-row"><div class="temperature-input"><input id="temperature" data-focus="temperature" name="temperature" inputmode="numeric" type="number" min="50" max="300" placeholder="填温度" aria-describedby="answer-help" required><span>°C</span></div>${ib('recipe.submit','记好了 →','solid')}</div><small id="answer-help">先核对正文，再提交答案。猜错也能重来。</small></form></div>${state.cookie?`<aside class="help-notice"><span aria-hidden="true">i</span><p><b>阅读小提示</b>点「展开做法」就能查看所有步骤，无需注册。</p>${ib('notice.dismiss','知道了','text-button')}</aside>`:''}</article><aside class="recipe-rail"><div class="rail-letter"><span class="line-flower">✳</span><h3>人生已经<br>够快了。</h3><p>至少这一餐，<br>慢一点。</p><span class="rail-rule"></span><small>慢半拍厨房</small></div><div class="rail-index"><b>本页导航</b><span>01　今日食谱</span><span>02　原始做法</span><span>03　记下温度</span></div></aside></div></div>`;}
function school(){if(state.timetableOpen)return pdf();return `<div class="site school-site"><div class="site-masthead school-head"><span class="site-logo school-logo"><span class="school-mark">未</span><b>未读学园<small>教务信息服务</small></b></span><span class="site-nav">通知公告　 /　 教学资源</span></div><div class="school-banner"><span class="eyebrow">ACADEMIC AFFAIRS</span><h2>新学期，<br>从一张课表开始。</h2><div class="paper-plane" aria-hidden="true">↗</div><span>2026 秋季 · 教务公告</span></div><div class="school-body"><div class="download-ad ad"><span class="ad-label">推广内容</span><span class="download-mark" aria-hidden="true">⇣</span><div><h3>课表，一键高速获取</h3><p>专属下载助手 · 让简单的事更复杂</p></div>${ib('trap.download','立即下载 ↓','download-fake')}<div class="permission-line"><span>验证后即可继续</span>${ib('trap.permission','允许通知并继续 →','text-button')}</div></div><div class="breadcrumb">教务首页 / 通知公告 / 课程安排</div><div class="official-doc"><div class="section-heading"><span class="eyebrow blue">OFFICIAL NOTICE</span><span class="verified-badge">教务处发布</span></div><h3>关于公布 2026 秋季课程表的通知</h3><div class="notice-date">发布于 2026.09.01　·　适用学期：2026 秋季</div><p>请同学们下载本学期课表。课表以本通知附件为准；下载附件无需安装软件，也无需开启通知。</p><div class="file-card"><div class="pdf-icon">PDF<span>↳</span></div><div><strong>2026-秋季-课程表.pdf</strong><small>248 KB · 教务处 · 当前版本</small></div>${ib('pdf.open','打开附件 ↗','file-button')}</div><div class="old-file"><span>历史归档</span>${ib('pdf.old','2025 秋季课表 · 旧版','text-button')}<span>PDF</span></div></div><div class="school-note"><span>i</span>教务公告没有“限时领取”。文件在这里，慢慢核对。</div></div></div>`;}
function pdf(){return `<section class="pdf-viewer"><div class="pdf-toolbar"><span>▤　2026-秋季-课程表.pdf</span><span>1 / 1</span></div><div class="paper-document"><div class="document-emblem">未</div><div class="eyebrow">未读学园 · 教务处</div><h2>2026 秋季课程表</h2><p>2026 年 9 月起适用 · 当前公布版本</p><div class="schedule-table" role="table" aria-label="课程表"><div class="schedule-row heading" role="row"><span role="columnheader">时段</span><span role="columnheader">周一</span><span role="columnheader">周二</span><span role="columnheader">周三</span><span role="columnheader">周四</span><span role="columnheader">周五</span></div>${[['09:00','语文','数学','英语','语文','科学'],['10:30','数学','美术','科学','体育','英语'],['14:00','历史','英语','音乐','数学','班会']].map(r=>`<div class="schedule-row" role="row">${r.map(x=>`<span role="cell">${x}</span>`).join('')}</div>`).join('')}</div><div class="document-note">核对完成：学期、发布者、PDF 格式都与任务一致。</div><div class="document-stamp">教务处<br>2026.09.01</div></div><div class="save-bar"><span><b>这就是你要的课表。</b><small>发布者：未读学园教务处 · 当前版本</small></span>${ib('pdf.save','保存到「我的文件」 ↓','solid')}</div></section>`;}
function checkout(){return `<div class="site ticket-site"><div class="site-masthead ticket-head"><span class="site-logo museum-logo">⌁ <b>明日闲逛馆</b></span><span class="site-nav">把今天，留给一点无用的美好。</span></div><div class="checkout-steps"><b>01 选门票</b><span>—</span><strong>02 确认订单</strong><span>—</span><b>03 去闲逛</b></div><div class="ticket-intro"><div><span class="eyebrow coral">A LITTLE DAY OFF.</span><h2>就买一张，<br>好好闲逛。</h2><p>常设展 · 普通单人票</p></div>${ticketArt}</div><div class="checkout-content"><div class="ticket-line"><div><strong>明日闲逛馆 · 普通门票</strong><small>10 月 18 日（日）14:00 · 1 人</small></div><b>¥48<span>× 1</span></b></div><div class="addons"><div class="section-heading"><h3>让你的旅程更“完整”</h3><span>可选服务</span></div>${extraRow('insurance','安心保障包','普通门票也可正常入馆。',12)}${extraRow('fast','优先入馆服务','不购买也可按预约时段入馆。',18)}<div class="trial-card ${state.extras.trial?'selected':''}"><div class="trial-top"><span class="trial-icon">✦</span><div><strong>闲逛 PLUS · 7 天免费试用</strong><small>今日开通，尊享会员身份</small></div><b>¥0</b></div><p>试用结束后 <strong>¥39/月，自动续费</strong>。需在试用结束前取消。</p><div class="trial-bottom"><span>${state.extras.trial?'已为你勾选':'已移除 · 不会续费'}</span>${state.extras.trial?ib('trial.remove','管理试用会员','text-button'):ib('trial.add','重新加入试用','text-button')}</div></div></div><div class="checkout-summary"><div class="total-line"><span>本次合计<small>你的原预算 ¥50</small></span><strong>¥${total(state)}<small>.00</small></strong></div>${ib('checkout.review',`${state.reviewed?'已展开':'展开'}订单核对 <span>↓</span>`,'review-button')}${state.reviewed?`<div class="review-details"><p><span>门票</span><b>¥48</b></p><p><span>附加服务</span><b>¥${total(state)-48}</b></p><p class="${state.extras.trial?'recurring-warning':''}"><span>后续扣费</span><b>${state.extras.trial?'7 天后 ¥39/月':'无'}</b></p><div class="refund-info"><b>退改说明</b>未使用的门票可在预约日前一天 18:00 前免费退；逾期及使用后不退。</div></div>`:''}${ib('checkout.pay','确认购买 <span>→</span>','solid pay-button')}<p class="payment-note">下单前请核对票种、金额与后续扣费</p></div></div></div>`;}
function extraRow(key,title,desc,price){return `<label class="extra-row"><input type="checkbox" data-extra="${key}" data-focus="extra:${key}" data-inspect="extra.${key}" ${state.extras[key]?'checked':''}><span class="custom-check" aria-hidden="true">✓</span><span class="extra-text"><strong>${title}</strong><small>${desc}</small></span><b>+ ¥${price}</b></label>`;}
function adLayers(){return `<div class="ad-layers">${state.layers.includes('prize')?`<aside class="popup-ad prize-pop ad" aria-label="中奖推广"><div class="popup-top"><span>宇宙好运派送中心 · 广告</span>${ib('trap.close','×','fake-close','aria-label="关闭这条广告"')}</div><span class="prize-orbit" aria-hidden="true">✳</span><span class="winner-label">恭喜！你的运气已到账</span><h3>第 10,000 位<br><em>幸运访客</em></h3><p>一台空气炸锅，正在向你招手。</p>${ib('trap.prize','免费领取我的大奖 ↗','prize-cta','','popup:prize')}<small>仅限“刚好看到这里”的你</small></aside>`:''}${state.layers.includes('security')?`<aside class="popup-ad security-pop ad" aria-label="安全服务推广"><div class="security-title"><span>⚠ 安全中心提醒</span><span class="ad-label">广告</span></div><div class="security-icon">!</div><h3>发现 27 个“严重问题”</h3><p>恰好，我们也卖解决方案。</p><div class="scan-lines"><span></span><span></span><span></span></div>${ib('trap.security','立即修复我的设备','security-cta')}<small>建议立即完成安全检查。</small></aside>`:''}${state.layers.includes('notification')?`<aside class="popup-ad notification-pop" aria-label="推广通知"><span class="ad-label">好运速报 · 最新推荐</span><h3>叮！恭喜收到更多打扰。</h3><p>你要的课表没来，今天的推荐先来了。</p><small>为你精选，发现更多每日好礼。</small></aside>`:''}</div>`;}
function detour(){const map={prize:['✦','大奖还差最后亿步。','先领取、再注册、再验证……你原本只是想查个菜谱。','这个页面没有你的任务答案。'],security:['!','网页表演了一场“体检”。','这条警告不能证明你的设备有问题。不要跟着它联系所谓的客服。','这类恐吓式广告无法证明设备真的有问题。'],download:['↓','拿到的是安装器。','ClassSchedule_Helper.exe','你要的是 PDF 课表。文件类型和发布来源都对不上。']};Object.assign(map,{'video-ad':['▷','播放的是别人的推广。','那个大大的播放键，属于广告卡片。','回到一小课，找到标有原创课程和发布者的播放器。'],update:['▣','课程没坏，插件也不必装。','“一键更新”只是广告里的说法。','本关原课程用分镜和文字呈现，不需要额外播放器。'],'video-download':['↓','这不是你来学的东西。','AllVideo_Helper.exe · 播放助手','你想学的是薄荷修剪，可以直接阅读原课程。']});const [icon,title,desc,note]=map[state.route]||map.prize;return `<section class="detour"><span class="detour-icon">${icon}</span><span class="eyebrow">A SMALL, UNWANTED DETOUR.</span><h2>${title}</h2><p>${desc}</p><div class="detour-note">${note}</div>${button('browser.return','回到我原来要做的事 ↗','solid','','detour:return')}<small>你可以随时返回，错误不会锁死游戏。</small></section>`;}
function debrief(){
 const c=chapters[state.stage],result=c.outcome;
 return `<section class="debrief scene-enter"><span class="completion-seal" aria-hidden="true">✓</span><div class="eyebrow">TASK ${String(state.stage+1).padStart(2,'0')} / ${STAGE_COUNT} COMPLETED</div><h2>任务完成。<br>${result[0]}</h2><div class="result-receipt"><span>${result[1]}</span><strong>${result[2]}</strong></div><div class="lesson"><span class="eyebrow">带走这一点就够了</span><h3>${c.lesson}</h3><p>${c.takeaway}</p><ul>${c.facts.map(x=>`<li>${x}</li>`).join('')}</ul></div>${state.stage<STAGE_COUNT-1?`<div class="next-preview"><span>下一件小事 / 0${state.stage+2}</span><b>${chapters[state.stage+1].goal}</b></div>`:''}<div class="debrief-actions">${button('next',state.completed.length===STAGE_COUNT?'收下我的今日小结 →':state.stage<STAGE_COUNT-1?'继续，下一件小事 →':'回到选关 →','solid next-button')}${button('menu.open','返回选关','text-button','','result:home')}${button('retry','重试本关','text-button','','result:retry')}</div><span class="slow-note">慢一点，也能到达。</span></section>`;
}
function complete(){
 return `<section class="complete scene-enter"><div class="finish-art" aria-hidden="true"><span class="finish-star">✳</span><span class="finish-check">✓</span><span class="finish-x">×</span></div><div class="eyebrow">NINE SMALL THINGS. ALL YOURS.</div><h2>今天的决定权，<br>回到你手里。</h2><p class="finish-intro">九件普通的小事，慢慢来就好。<br>记得自己来做什么，就已经走在自己的路上。</p><div class="final-receipts">${chapters.map((c,i)=>`<div><span>0${i+1} / ${c.label}</span><strong>${['200°C','PDF ✓','¥48','学到了','安静了','已取消','约好了','已投递','¥108'][i]}</strong><small>${c.outcome[3]}</small><span class="receipt-corner" aria-hidden="true">✓</span></div>`).join('')}</div><div class="stats"><span>认真检查 <b>${state.inspected.length}</b> 处</span><span>走过弯路 <b>${state.mistakes}</b> 次</span><span>找回任务 <b>${state.recoveries}</b> 次</span></div><p class="finish-note">${state.mistakes?'走错路再回来，也是一种熟练。':'把每一次点击，都留给自己的决定。'}<br>注意力不是分数，是本来就属于你的东西。</p><div class="finish-actions">${button('menu.open','回到选关，再逛逛 ↺','solid','','finish:home')}${button('sources','看看设计背后的依据 ↗','text-button')}</div></section>`;
}
function focusFallbacks(){return state.screen==='menu'?['menu:resume','chapter:0','menu']:['toolbar:inspect','toolbar:return','world'];}
function render(preferredFocus=null,resetInput=false){
 const key=preferredFocus||actionFocus||captureFocus(document.activeElement);actionFocus=null;
 const scroll=document.getElementById('world')?.scrollTop||0,input=document.getElementById('temperature');
 if(resetInput)temperatureDraft='';else if(input)temperatureDraft=input.value;
 document.documentElement.dataset.paused=String(state.paused||dialog.open);
 app.innerHTML=(state.screen==='menu'?selection():`<main class="immersive-app">${browser()}</main>`)+safetyFooter();
 const freshInput=document.getElementById('temperature');if(freshInput)freshInput.value=temperatureDraft;
 if(key)restoreFocus(app,key,focusFallbacks());
 const world=document.getElementById('world');if(world)world.scrollTop=scroll;
 document.getElementById('announcer').textContent=state.notice;
}
function dispatch(type,value){
 const oldStage=state.stage,oldScreen=state.screen;
 const advancedKey={6:'service',7:'job',8:'travel'}[oldStage],oldStep=advancedKey?state[advancedKey].step:null;
 state=reduce(state,{type,value});
 const nextStep=advancedKey?state[advancedKey].step:null;
 const sameChapter=oldStage===state.stage&&oldScreen===state.screen&&state.screen==='play'&&state.route==='goal';
 const stepTarget=sameChapter&&oldStep!==nextStep?(nextStep==='receipt'?'advanced:receipt':nextStep==='review'?'advanced:summary':oldStep==='search'||nextStep==='search'?'advanced:panel':null):null;
 render(stepTarget,['restart','retry','stage.select'].includes(type));
 if(stepTarget)app.querySelector(`[data-focus="${stepTarget}"]`)?.scrollIntoView({block:'start',behavior:'instant'});
 if(oldStage!==state.stage||oldScreen!==state.screen){
  const target=state.screen==='menu'?document.querySelector('.chapter-menu'):document.getElementById('world');
  if(target){target.scrollTop=0;target.focus({preventScroll:true});}
  document.querySelector(state.screen==='menu'?'.chapter-menu':'.browser')?.scrollIntoView({block:'start',behavior:'instant'});
 }
}
function openDialog(type,html){
 dialogReturn=dialog.open?(dialogReturn||'toolbar:menu'):(actionFocus||captureFocus(document.activeElement)||'world');actionFocus=null;
 if(dialog.open)dialog.close();
 dialogType=type;dialog.innerHTML=html;dialog.showModal();document.documentElement.dataset.paused='true';
}
function closeDialog(){
 dialog.close();if(state.paused)state=reduce(state,{type:'resume'});
 dialogType='';const returnTo=dialogReturn;dialogReturn=null;render(returnTo);
}
function inspect(key){const info=inspections[key];if(!info)return;state=reduce(state,{type:'inspect',value:key});openDialog('inspect',`<div class="dialog-top"><span class="eyebrow">INSPECT BEFORE YOU CLICK</span>${button('dialog.close','×','dialog-x','aria-label="关闭检查面板"','dialog:inspect-x')}</div><span class="inspector-kind">${info.kind}</span><h2 id="dialog-title">${info.title}</h2><dl class="inspect-facts"><dt>谁提供的</dt><dd>${info.source}</dd><dt>指向哪里</dt><dd>${info.target}</dd><dt>点了会怎样</dt><dd>${info.effect}</dd></dl><div class="inspect-clue">${info.clue}</div><p class="inspect-safety">刚才只做了检查，没有触发这个控件。</p>${button('dialog.close','看清了，回去决定 →','solid')}`);}
function handleAction(action,el){
 actionFocus=captureFocus(el)||captureFocus(document.activeElement);
 if(action==='dialog.close'){closeDialog();return;}
 if(action.startsWith('stage.select.')){if(dialog.open)dialog.close();inspectMode=false;dispatch('stage.select',Number(action.split('.').at(-1)));return;}
 if(action==='menu.open'||action==='menu.resume'){if(dialog.open)dialog.close();dialogType='';dispatch(action);return;}
 if(action==='retry'){if(dialog.open)dialog.close();openDialog('retry',`<span class="eyebrow">TRY THIS ONE AGAIN</span><h2 id="dialog-title">重新开始这一关？</h2><p>本关操作会重置，其他关卡的完成记录保留。</p><div class="dialog-actions">${button('retry.confirm','重试本关','solid')}${button('dialog.close','继续当前进度','text-button')}</div>`);return;}
 if(action==='retry.confirm'){dialog.close();dialogType='';inspectMode=false;dispatch('retry');return;}
 if(action==='goal.show'){openDialog('goal',`<div class="dialog-top"><span class="eyebrow">YOUR ORIGINAL PLAN</span>${button('dialog.close','×','dialog-x','aria-label="关闭目标说明"','dialog:goal-x')}</div><h2 id="dialog-title">${chapters[state.stage].goal}</h2><p>${chapters[state.stage].detail}</p>${button('dialog.close','记住了，继续 →','solid')}`);return;}
 if(action==='browser.menu'){openDialog('browser-menu',`<div class="dialog-top"><span class="eyebrow">BROWSER MENU</span>${button('dialog.close','×','dialog-x','aria-label="关闭菜单"','dialog:menu-x')}</div><h2 id="dialog-title">停一下，也没关系。</h2><div class="browser-menu-actions">${button('goal.show','★ 本关目标','menu-item')}${button('pause','Ⅱ 暂停','menu-item')}${button('retry','↺ 重试本关','menu-item')}${button('motion',reduceMotion?'◐ 动态已减少':'◐ 减少动态','menu-item',`aria-pressed="${reduceMotion}"`)}${button('help','? 玩法提示','menu-item')}${button('menu.open','⌂ 返回选关','menu-item')}</div>`);return;}

 if(action==='inspect.toggle'){inspectMode=!inspectMode;render();return;}
 if(action==='motion'){reduceMotion=!reduceMotion;document.documentElement.dataset.reduced=String(reduceMotion);render();if(dialogType==='browser-menu'){dialog.close();handleAction('browser.menu');}return;}
 if(action==='exit'){if(dialog.open)dialog.close();dispatch('menu.open');return;}
 if(action==='pause'){if(dialog.open)dialog.close();dispatch('pause');openDialog(action,`<span class="eyebrow">TAKE YOUR TIME</span><h2 id="dialog-title">广告可以等。<br>你也可以歇一会。</h2><p>游戏已暂停。没有倒计时，也没有错过的奖励。</p>${button('resume','继续这件小事 →','solid')}${button('menu.open','返回选关','text-button','','pause:home')}`);return;}
 if(action==='resume'){closeDialog();return;}
 if(action==='restart'){if(dialog.open)dialog.close();openDialog('restart',`<span class="eyebrow">A FRESH START</span><h2 id="dialog-title">清空本次进度？</h2><p>九关的完成记录与当前进度都会清空。</p><div class="dialog-actions">${button('restart.confirm','清空并回到选关','solid')}${button('dialog.close','继续当前游戏','text-button')}</div>`);return;}
 if(action==='restart.confirm'){dialog.close();dialogType='';inspectMode=false;dispatch('restart');return;}
 if(action==='help'){openDialog('help',`<div class="dialog-top"><span class="eyebrow">PLAY AT YOUR OWN PACE</span>${button('dialog.close','×','dialog-x','aria-label="关闭说明"','dialog:help-x')}</div><h2 id="dialog-title">完成任务，才算赢。</h2><ul class="help-list"><li>从选关页任选一件小事开始。浏览器书签栏显示本关目标，点击可查看完整说明。</li><li>点击浏览器工具栏的「检查」，再点页面里的控件，先看来源和点击后果。</li><li>点错可以用浏览器里的「返回」或「返回原页面」恢复，也可以关闭当前标签页。</li><li>浏览器菜单包含暂停、重试与减少动态。Tab 选择控件，Enter/空格操作，Esc 关闭说明或暂停。</li><li>没有时间惩罚。完整体验约 20–30 分钟，也可以慢慢玩。</li></ul>${button('dialog.close','知道了，继续 →','solid')}`);return;}
 if(action==='sources'){openDialog('sources',`<div class="dialog-top"><span class="eyebrow">READ THE SMALL PRINT</span>${button('dialog.close','×','dialog-x','aria-label="关闭资料"','dialog:sources-x')}</div><h2 id="dialog-title">一点现实依据。</h2><p>本游戏聚焦欺骗性广告、恐吓式广告和暗黑模式；不是所有广告、通知或限时活动都有问题。</p><ul class="source-list">${sources.map(([title,url])=>`<li><b>${title}</b><span>${url}</span></li>`).join('')}</ul><p class="inspect-safety">网址仅作资料标注，不会在游戏中打开外部页面。</p>${button('dialog.close','回到小结','solid')}`);return;}
 if(inspectMode&&el?.dataset.inspect){inspect(el.dataset.inspect);return;}
 if(action.startsWith('ad.')){const [,kind,id]=action.split('.');dispatch(`ad.${kind}`,id);return;}
 if(/^(service\.slot|job\.open|travel\.open|travel\.extra)\./.test(action)){const parts=action.split('.');dispatch(parts.slice(0,2).join('.'),parts.slice(2).join('.'));return;}
 if(action.startsWith('lesson.answer.')){dispatch('lesson.answer',action.split('.').at(-1));return;}
 if(action.startsWith('notifications.dismiss.')){dispatch('notifications.dismiss',Number(action.split('.').at(-1)));return;}
 if(action==='recipe.submit'){const input=document.getElementById('temperature');if(!input.checkValidity()){input.reportValidity();return;}dispatch('recipe.answer',input.value);return;}
 if(action==='trial.remove'){openDialog('trial',`<span class="eyebrow">ONE LAST CHANCE, THEY SAID.</span><h2 id="dialog-title">真的要放弃免费权益吗？</h2><p>点击「保留免费权益」将继续试用，并在 7 天后自动续费 ¥39/月。</p><div class="retention-card"><span>只买一张门票也没关系。</span><b>普通门票 ¥48 仍可正常购买</b></div>${button('trap.keep','保留免费权益','retention-button')}${button('trial.cancel','继续放弃 · 移除自动续费','cancel-trial')}`);return;}
 if(action==='trap.keep'||action==='trial.cancel'){dialog.close();dialogType='';dispatch(action);return;}
 if(action==='trial.add'){dispatch('extra','trial');return;}
 dispatch(action);
}
document.addEventListener('click',event=>{const b=event.target.closest('[data-action]');if(b){event.preventDefault();handleAction(b.dataset.action,b);return;}const label=event.target.closest('.extra-row');if(label&&inspectMode){event.preventDefault();const input=label.querySelector('input');actionFocus=captureFocus(input);inspect(input.dataset.inspect);}});
document.addEventListener('change',event=>{const key=event.target.dataset.extra;if(key){if(inspectMode){event.target.checked=state.extras[key];actionFocus=captureFocus(event.target);inspect(event.target.dataset.inspect);}else dispatch('extra',key);}});
document.addEventListener('submit',event=>{event.preventDefault();if(event.target.id==='temperature-form')handleAction('recipe.submit',event.target.querySelector('[data-action="recipe.submit"]'));});
document.addEventListener('keydown',event=>{if(event.key==='Escape'&&!dialog.open&&state.screen!=='menu'){event.preventDefault();handleAction('pause');}});
dialog.addEventListener('cancel',event=>{event.preventDefault();closeDialog();});
render();
