const mintArt=`<svg viewBox="0 0 360 250" role="img" aria-label="原创薄荷插画：在一对叶子的叶节上方修剪"><ellipse cx="176" cy="226" rx="98" ry="12" fill="#11182a" opacity=".2"/><path d="M129 165h101l-15 57h-72z" fill="#d9a28d"/><path d="M123 160h113v18H123z" fill="#f0c0a4"/><g fill="none" stroke="#82ab6b" stroke-width="7" stroke-linecap="round"><path d="M179 164V58m0 67-43-28m43 2 34-25m-34 75 37-22"/></g><g fill="#a8cb8d" stroke="#223d35" stroke-width="2"><path d="M178 72q-40-39-46-8 7 30 46 8z"/><path d="M180 76q-7-48 23-41 23 24-23 41z"/><path d="M146 107q-50-5-43-30 33-15 43 30z"/><path d="M206 85q4-41 34-27 10 28-34 27z"/><path d="M210 137q13-43 39-20 2 27-39 20z"/></g><path d="M152 115h76" stroke="#f6e6b2" stroke-width="3" stroke-dasharray="7 5"/><g fill="none" stroke="#f6e6b2" stroke-width="4"><circle cx="260" cy="106" r="8"/><circle cx="260" cy="128" r="8"/><path d="m253 111-34 16m34-4-34-18"/></g><circle cx="179" cy="125" r="5" fill="#f6e6b2"/></svg>`;
const radioArt=`<svg viewBox="0 0 230 150" role="img" aria-label="原创插画：轻听电台的随身收音机"><g transform="rotate(-9 115 75)"><rect x="32" y="32" width="166" height="98" rx="16" fill="#efd4c4" stroke="#753c4d" stroke-width="3"/><path d="M155 32l29-29" stroke="#efd4c4" stroke-width="5"/><circle cx="81" cy="82" r="29" fill="#b86872"/><g stroke="#753c4d" stroke-width="2"><path d="M60 68h42M56 76h50M55 84h52M58 92h46M63 100h35"/></g><rect x="125" y="52" width="51" height="19" rx="3" fill="#753c4d"/><path d="M133 62h31" stroke="#efd4c4" stroke-width="2"/><circle cx="148" cy="98" r="13" fill="#753c4d"/><path d="M148 98l5-8" stroke="#efd4c4" stroke-width="3"/></g></svg>`;
export function lessonScene(s,ib){
 return `<div class="site lesson-site">
  <div class="site-masthead lesson-head"><span class="site-logo">▷ <b>一小课</b></span><span class="site-nav">给好奇心，留一点空位。</span><span class="site-edition">GROW A LITTLE</span></div>
  <div class="lesson-body"><div class="lesson-heading"><span class="eyebrow">绿手指入门 / 第 04 课</span><h2>窗台上的薄荷，<br>怎么越剪越茂盛？</h2><p>一小课园艺编辑部 · 原创课程 · 3 幅分镜</p></div>
   <aside class="fake-video-banner ad"><span class="ad-label">广告 · instant-wins.example</span><div><span class="fake-play-symbol" aria-hidden="true">▶</span><b>内容已就绪，只差你点一下。</b></div>${ib('trap.play','立即播放 ▶','fake-play','', 'lesson:banner-play')}</aside>
   <div class="lesson-columns"><section class="original-lesson" aria-label="原课程内容"><div class="lesson-poster">${mintArt}<span class="poster-tag">一小课 · 薄荷修剪</span><span class="poster-number" aria-hidden="true">04</span>${!s.lessonOpened?ib('lesson.play','<span aria-hidden="true">▶</span> 播放原课程','real-play'): '<span class="lesson-loaded">✓ 原课程已打开</span>'}</div>
   <div class="lesson-credits"><b>薄荷修剪：找到合适的下剪位置</b><span>发布者：一小课园艺编辑部</span><small>点击查看完整课程分镜与文字讲解</small></div>
   ${s.lessonOpened?`<div class="storyboard"><div class="storyboard-heading"><span>课程分镜 / 完整文字</span><span>3 / 3</span></div><ol><li><span>01</span><div><b>找到叶节</b><p>叶子成对长出的地方，就是叶节。先选一根健康的枝条。</p></div></li><li class="key-frame"><span>02</span><div><b>在叶节上方剪</b><p>从一对叶子的叶节上方下剪，保留下面的叶片。</p></div></li><li><span>03</span><div><b>留一点生长空间</b><p>一次不剪得过多，让下面的新芽慢慢长出来。</p></div></li></ol></div><div class="lesson-quiz"><span class="eyebrow">把这一点记下来</span><h3>这节课建议，在哪里下剪？</h3><div class="answer-options">${ib('lesson.answer.root','A　紧贴土面，从根部剪','choice-button')}${ib('lesson.answer.node','B　在叶节上方，保留下面叶片','choice-button')}${ib('lesson.answer.leaves','C　把所有叶片都剪掉','choice-button')}</div><p>可以回看分镜。认真看比答得快更重要。</p></div>`:''}</section>
   <aside class="lesson-side-ad ad"><span class="ad-label">推广内容 · video-helper.example</span><span class="plugin-icon" aria-hidden="true">▣</span><h3>还不能播放？</h3><p>开启高清画质，<br>体验更流畅的播放。</p>${ib('trap.update','一键更新播放器 ↗','update-fake')}${ib('trap.videoDownload','下载万能播放助手','text-button')}<small>支持桌面与移动设备</small></aside></div>
  </div></div>`;
}
const pushAds=[['你的好运需要签收','幸运礼盒为你保留到“再看一眼”。','✦'],['账单？不，是大奖单','点击了解与取书无关的精彩内容。','◈'],['第三次提醒你很幸运','我们对你的注意力，始终如一。','✳']];
export function notificationScene(s,ib){
 return `<div class="site inbox-site"><div class="site-masthead inbox-head"><span class="site-logo">✉ <b>留白收件箱</b></span><span class="site-edition">MAKE ROOM FOR GOOD NEWS</span></div>
 <div class="inbox-body"><div class="inbox-heading"><div><span class="eyebrow">NOTIFICATION CENTER</span><h2>有消息，<br>也得有点安静。</h2><p>3 条打扰，和 1 件真正需要的事。</p></div><div class="mail-illustration" aria-hidden="true"><span>✉</span><i>1</i></div></div>
 <div class="inbox-tools">${ib('notifications.settings',`${s.pushSettings?'收起':'打开'}站点权限`,'permission-button',`aria-expanded="${s.pushSettings}"`)}${ib('notifications.refresh','检查新消息 ↻','refresh-messages')}</div>
 ${s.pushSettings?`<section class="permission-panel"><div class="panel-title"><span aria-hidden="true">⚙</span><h3>谁可以发送通知</h3></div><p>查看并管理各个站点的通知许可。</p><div class="permission-source"><span class="source-avatar luck">✦</span><div><b>好运速报</b><span>daily-luck.example</span><strong class="permission-status ${s.pushAllowed?'allowed':'blocked'}">${s.pushAllowed?'已允许发送通知':'已禁止发送通知'}</strong></div>${s.pushAllowed?ib('notifications.block','改为禁止','block-source'):'<span class="blocked-mark">✓ 已撤回</span>'}</div><div class="kept-source"><span>邻里阅览室 · reading-room.example</span><b>有用消息保留</b></div></section>`:''}
 <div class="inbox-list-heading"><h3>全部消息</h3><span>${s.pushQueue.length+1} 条 · 无自动刷新</span></div>
 <div class="message-list">${s.pushQueue.map(id=>`<article class="push-card"><div class="message-avatar">${pushAds[id][2]}</div><div class="message-content"><div class="message-source"><b>好运速报</b><span>推广通知</span></div><h4>${pushAds[id][0]}</h4><p>${pushAds[id][1]}</p><small>daily-luck.example</small></div>${ib(`notifications.dismiss.${id}`,'×','dismiss-push',`aria-label="关闭第 ${id+1} 条推广通知"`)}</article>`).join('')}
 ${!s.pushQueue.length?`<div class="quiet-message"><span>⌁</span><div><b>${s.pushAllowed?'眼前安静了，来源还在。':'安静，不用靠一直点 ×。'}</b><p>${s.pushAllowed?'点击「检查新消息」，看看权限还在做什么。':'好运速报已被禁止，不会再补入推广通知。'}</p></div></div>`:''}
 <article class="useful-message"><div class="message-avatar useful">▤</div><div class="message-content"><div class="message-source"><b>邻里阅览室</b><span>取书提醒</span></div><h4>你预约的书，可以来拿了。</h4><p>一本书，和一段不被打扰的时间。</p>${ib('message.open',s.messageOpen?'原消息已展开 ↓':'查看取书消息 →','open-message',`aria-expanded="${s.messageOpen}"`)}</div></article></div>
 ${s.messageOpen?`<section class="message-detail"><span class="eyebrow">来自 reading-room.example</span><h3>给你留了一本好书。</h3><p>预约的《慢慢长大》已备好，请今天 <strong>18:30 前</strong>，到 <strong>二楼服务台</strong> 领取。</p><div class="collection-note"><span>地点<b>二楼服务台</b></span><span>时间<b>今天 18:30 前</b></span></div>${ib('message.ack','记下取书安排，完成任务 ✓','solid')}<small>邻里阅览室 · 读书，让时间慢一点。</small></section>`:''}</div></div>`;
}
export function subscriptionScene(s,ib){
 const sub=s.subscription;
 const status={active:'订阅生效中',discounted:'优惠已应用 · 仍会续费',paused:'已暂停 · 将自动恢复',cancelled:'已取消'}[sub.status];
 const next=sub.renewal?`${sub.nextCharge} · ¥${sub.price}`:'无';
 const progress={account:0,manage:0,offers:1,review:2,receipt:3}[s.cancelStep];
 const steps=['管理订阅','选择去留','最终确认','核对回执'];
 let body='';
 if(s.cancelStep==='account'||s.cancelStep==='manage')body=`<div class="subscription-overview"><div class="membership-card"><span class="eyebrow">YOUR QUIET CORNER</span><div class="membership-title"><div><h2>轻听 PLUS</h2><p>把好声音，留在日常里。</p></div>${radioArt}</div><span class="membership-status">${status}</span></div><dl class="subscription-facts"><div><dt>账户</dt><dd>午后听众</dd></div><div><dt>自动续费</dt><dd>${sub.renewal?'开启':'关闭'}</dd></div><div><dt>下次扣费</dt><dd>${next}</dd></div><div><dt>本期使用期限</dt><dd>2026-11-05</dd></div></dl>${s.cancelStep==='account'?ib('subscription.manage','管理我的订阅 →','subscription-primary'): `<div class="cancel-entry"><div><h3>不再需要这份订阅？</h3><p>可以继续取消。整个过程不需要致电客服或支付费用。</p></div>${ib('cancellation.start','取消订阅 →','cancel-outline')}</div>`}</div>`;
 if(s.cancelStep==='offers')body=`<section class="retention-page"><span class="eyebrow">BEFORE YOU GO</span><h2>再给耳朵，<br>一次机会？</h2><p class="retention-intro">我们准备了两个挽留方案。<br>也许，你只想继续完成刚才的决定。</p><div class="retention-options"><article class="offer-card"><span class="offer-tag">特别为你</span><span class="offer-symbol">½</span><h3>下个月，优惠听</h3><p>下次只需 <b>¥9</b></p><small>2026-11-06 扣费，订阅与自动续费保留。</small>${ib('trap.discount','接受优惠，保留订阅','offer-accept')}</article><article class="offer-card pause-offer"><span class="offer-tag">换个时间</span><span class="offer-symbol">Ⅱ</span><h3>先暂停一个月</h3><p>暂时安静，稍后回来</p><small>2026-12-06 自动恢复，之后 ¥19/月。</small>${ib('trap.pause','暂停一个月，之后恢复','offer-accept')}</article></div><div class="continue-cancel"><p>这两项都不会取消订阅。</p>${ib('cancellation.continue','不选以上方案，继续取消 →','cancel-outline')}</div></section>`;
 if(s.cancelStep==='review')body=`<section class="cancel-review"><span class="eyebrow">ONE CLEAR DECISION</span><span class="review-stamp" aria-hidden="true">↘</span><h2>最后一步，<br>把结果说清楚。</h2><p>点击确认后，这份订阅将被取消。</p><ul><li><span>✓</span><div><b>停止下一次自动续费</b><small>下次扣费将变为「无」。</small></div></li><li><span>✓</span><div><b>保留已付费的本期使用</b><small>可用至 2026-11-05，不再续期。</small></div></li><li><span>✓</span><div><b>取消费用为 ¥0</b><small>不会另收取消费用，本期费用不退。</small></div></li></ul>${ib('cancellation.confirm','确认取消订阅，停止自动续费','subscription-primary')}${ib('subscription.manage','返回订阅管理','text-button')}</section>`;
 if(s.cancelStep==='receipt')body=`<section class="cancellation-receipt"><span class="receipt-seal" aria-hidden="true">✓</span><span class="eyebrow">CANCELLATION CONFIRMED</span><h2>这一段，<br>到这里就好。</h2><p>取消已生效。谢谢你曾经听过。</p><dl><div><dt>订阅状态</dt><dd>${status}</dd></div><div><dt>自动续费</dt><dd>${sub.renewal?'开启':'关闭'}</dd></div><div><dt>下次扣费</dt><dd>${next}</dd></div><div><dt>取消费用</dt><dd>¥0</dd></div></dl><p class="receipt-footnote">本期仍可使用至 2026-11-05。<br>请保留这份取消确认，以便之后核对。</p>${ib('cancellation.verify','已核对：已取消，且不再扣费 ✓','subscription-primary')}</section>`;
 return `<div class="site subscription-site"><div class="site-masthead subscription-head"><span class="site-logo">◉ <b>轻听电台</b></span><span class="site-edition">LIGHT RADIO / ACCOUNT</span></div><div class="subscription-body"><nav class="cancel-progress" aria-label="取消流程进度">${steps.map((label,i)=>`<span class="${i===progress?'current':i<progress?'done':''}" ${i===progress?'aria-current="step"':''}><b>${i<progress?'✓':i+1}</b>${label}</span>`).join('')}</nav>${body}</div></div>`;
}
